// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TBallGift : table.ITBallGiftDefine[] = [
		{ Id : 1, Name : "200金币", Num : 200, ItemId : 60003, Path : "item_json.6003", Pro : 1334, PushBag : 1, Cost : 1 	},
		{ Id : 2, Name : "50元京东卡", Num : 1, ItemId : 20006, Path : "item_json.2006", Pro : 50, PushBag : 1, Cost : 50 	},
		{ Id : 3, Name : "10元电话卡", Num : 1, ItemId : 50004, Path : "item_json.5004", Pro : 100, PushBag : 1, Cost : 10 	},
		{ Id : 4, Name : "100钻石", Num : 100, ItemId : 60002, Path : "item_json.6002", Pro : 1000, PushBag : 1, Cost : 5 	},
		{ Id : 5, Name : "60钻石", Num : 60, ItemId : 60002, Path : "item_json.6002", Pro : 1000, PushBag : 1, Cost : 3 	},
		{ Id : 6, Name : "1000金币", Num : 1000, ItemId : 60003, Path : "item_json.6003", Pro : 5, PushBag : 1, Cost : 840 	},
		{ Id : 7, Name : "2000金币", Num : 2000, ItemId : 60003, Path : "item_json.6003", Pro : 350, PushBag : 1, Cost : 10 	},
		{ Id : 8, Name : "600金币", Num : 600, ItemId : 60003, Path : "item_json.6003", Pro : 10, PushBag : 1, Cost : 200 	},
		{ Id : 9, Name : "5000金币", Num : 5000, ItemId : 60003, Path : "item_json.6003", Pro : 200, PushBag : 1, Cost : 5000 	},
		{ Id : 10, Name : "600金币", Num : 600, ItemId : 60003, Path : "item_json.6003", Pro : 1, PushBag : 1, Cost : 8488 	},
		{ Id : 11, Name : "400金币", Num : 400, ItemId : 60003, Path : "item_json.6003", Pro : 1200, PushBag : 1, Cost : 2 	},
		{ Id : 12, Name : "30元电话卡", Num : 1, ItemId : 50003, Path : "item_json.5003", Pro : 100, PushBag : 1, Cost : 30 	},
		{ Id : 13, Name : "20钻石", Num : 20, ItemId : 60002, Path : "item_json.6002", Pro : 1300, PushBag : 1, Cost : 1 	},
		{ Id : 14, Name : "50元京东卡", Num : 1, ItemId : 20006, Path : "item_json.2006", Pro : 50, PushBag : 1, Cost : 50 	},
		{ Id : 15, Name : "10元电话卡", Num : 1, ItemId : 50004, Path : "item_json.5004", Pro : 100, PushBag : 1, Cost : 10 	},
		{ Id : 16, Name : "1000金币", Num : 1000, ItemId : 60003, Path : "item_json.6003", Pro : 1000, PushBag : 1, Cost : 5 	},
		{ Id : 17, Name : "600金币", Num : 600, ItemId : 60003, Path : "item_json.6003", Pro : 1000, PushBag : 1, Cost : 3 	},
		{ Id : 18, Name : "40钻", Num : 40, ItemId : 60002, Path : "item_json.6002", Pro : 1200, PushBag : 1, Cost : 2 	}
	]


// Id
export var TBallGiftById : game.Dictionary<table.ITBallGiftDefine> = {}
function readTBallGiftById(){
  for(let rec of TBallGift) {
    TBallGiftById[rec.Id] = rec; 
  }
}
readTBallGiftById();
}

