// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var Card : table.ICardDefine[] = [
		{ Id : 1, Type : 1, Index : 1 	},
		{ Id : 2, Type : 1, Index : 2 	},
		{ Id : 3, Type : 1, Index : 3 	},
		{ Id : 4, Type : 1, Index : 4 	},
		{ Id : 5, Type : 1, Index : 5 	},
		{ Id : 6, Type : 1, Index : 6 	},
		{ Id : 7, Type : 1, Index : 7 	},
		{ Id : 8, Type : 1, Index : 8 	},
		{ Id : 9, Type : 1, Index : 9 	},
		{ Id : 10, Type : 1, Index : 10 	},
		{ Id : 11, Type : 1, Index : 11 	},
		{ Id : 12, Type : 1, Index : 12 	},
		{ Id : 13, Type : 1, Index : 13 	},
		{ Id : 14, Type : 2, Index : 1 	},
		{ Id : 15, Type : 2, Index : 2 	},
		{ Id : 16, Type : 2, Index : 3 	},
		{ Id : 17, Type : 2, Index : 4 	},
		{ Id : 18, Type : 2, Index : 5 	},
		{ Id : 19, Type : 2, Index : 6 	},
		{ Id : 20, Type : 2, Index : 7 	},
		{ Id : 21, Type : 2, Index : 8 	},
		{ Id : 22, Type : 2, Index : 9 	},
		{ Id : 23, Type : 2, Index : 10 	},
		{ Id : 24, Type : 2, Index : 11 	},
		{ Id : 25, Type : 2, Index : 12 	},
		{ Id : 26, Type : 2, Index : 13 	},
		{ Id : 27, Type : 3, Index : 1 	},
		{ Id : 28, Type : 3, Index : 2 	},
		{ Id : 29, Type : 3, Index : 3 	},
		{ Id : 30, Type : 3, Index : 4 	},
		{ Id : 31, Type : 3, Index : 5 	},
		{ Id : 32, Type : 3, Index : 6 	},
		{ Id : 33, Type : 3, Index : 7 	},
		{ Id : 34, Type : 3, Index : 8 	},
		{ Id : 35, Type : 3, Index : 9 	},
		{ Id : 36, Type : 3, Index : 10 	},
		{ Id : 37, Type : 3, Index : 11 	},
		{ Id : 38, Type : 3, Index : 12 	},
		{ Id : 39, Type : 3, Index : 13 	},
		{ Id : 40, Type : 4, Index : 1 	},
		{ Id : 41, Type : 4, Index : 2 	},
		{ Id : 42, Type : 4, Index : 3 	},
		{ Id : 43, Type : 4, Index : 4 	},
		{ Id : 44, Type : 4, Index : 5 	},
		{ Id : 45, Type : 4, Index : 6 	},
		{ Id : 46, Type : 4, Index : 7 	},
		{ Id : 47, Type : 4, Index : 8 	},
		{ Id : 48, Type : 4, Index : 9 	},
		{ Id : 49, Type : 4, Index : 10 	},
		{ Id : 50, Type : 4, Index : 11 	},
		{ Id : 51, Type : 4, Index : 12 	},
		{ Id : 52, Type : 4, Index : 13 	}
	]


// Id
export var CardById : game.Dictionary<table.ICardDefine> = {}
function readCardById(){
  for(let rec of Card) {
    CardById[rec.Id] = rec; 
  }
}
readCardById();
}

