// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var Championship : table.IChampionshipDefine[] = [
		{ Id : 4, Name : "免费-20万金币赛", Type : 1, Icon : "match_1", SNum : 3, BNum : 600, SignCost : 0, ServeCost : 0, RebuyCost : 500, AddonCost : 500, TicketId : 0, TimeId : 101, DisplayTime : 1800, SignTime : 1800, DelaySign : 600, Rebuy : 6, Addon : 1, Prize : 101, BlindType : 101, InitialChips : 3000, RoomId : 21001, WaitingTime : 0, AddonChips : 6000, MaxRebuyTimes : 2, Autoinit : 1 	},
		{ Id : 5, Name : "100万金币欢乐赛", Type : 1, Icon : "match_2", SNum : 3, BNum : 800, SignCost : 5000, ServeCost : 500, RebuyCost : 5000, AddonCost : 5000, TicketId : 105, TimeId : 102, DisplayTime : 7200, SignTime : 7200, DelaySign : 1200, Rebuy : 6, Addon : 1, Prize : 102, BlindType : 102, InitialChips : 3000, RoomId : 21001, WaitingTime : 0, AddonChips : 6000, MaxRebuyTimes : 2, Autoinit : 1 	},
		{ Id : 101, Name : "500金币争霸场", Type : 2, Icon : "match_1", SNum : 3, BNum : 12, SignCost : 500, ServeCost : 50, RebuyCost : 0, AddonCost : 0, TicketId : 0, TimeId : 301, DisplayTime : 0, SignTime : 0, DelaySign : 0, Rebuy : 0, Addon : 0, Prize : 201, BlindType : 201, InitialChips : 3000, RoomId : 22001, WaitingTime : 8, AddonChips : 0, MaxRebuyTimes : 0, Autoinit : 0 	},
		{ Id : 102, Name : "1000金币争霸场", Type : 2, Icon : "match_1", SNum : 3, BNum : 12, SignCost : 1000, ServeCost : 100, RebuyCost : 0, AddonCost : 0, TicketId : 0, TimeId : 301, DisplayTime : 0, SignTime : 0, DelaySign : 0, Rebuy : 0, Addon : 0, Prize : 202, BlindType : 201, InitialChips : 3000, RoomId : 22001, WaitingTime : 8, AddonChips : 0, MaxRebuyTimes : 0, Autoinit : 0 	},
		{ Id : 103, Name : "5000金币争霸场", Type : 2, Icon : "match_1", SNum : 3, BNum : 12, SignCost : 5000, ServeCost : 500, RebuyCost : 0, AddonCost : 0, TicketId : 0, TimeId : 301, DisplayTime : 0, SignTime : 0, DelaySign : 0, Rebuy : 0, Addon : 0, Prize : 203, BlindType : 201, InitialChips : 3000, RoomId : 22001, WaitingTime : 8, AddonChips : 0, MaxRebuyTimes : 0, Autoinit : 0 	},
		{ Id : 121, Name : "单挑-5万金币场", Type : 2, Icon : "match_1", SNum : 2, BNum : 2, SignCost : 50000, ServeCost : 5000, RebuyCost : 0, AddonCost : 0, TicketId : 0, TimeId : 301, DisplayTime : 0, SignTime : 0, DelaySign : 0, Rebuy : 0, Addon : 0, Prize : 241, BlindType : 202, InitialChips : 4000, RoomId : 22001, WaitingTime : 8, AddonChips : 0, MaxRebuyTimes : 0, Autoinit : 0 	},
		{ Id : 122, Name : "单挑-10万金币场", Type : 2, Icon : "match_1", SNum : 2, BNum : 2, SignCost : 100000, ServeCost : 10000, RebuyCost : 0, AddonCost : 0, TicketId : 0, TimeId : 301, DisplayTime : 0, SignTime : 0, DelaySign : 0, Rebuy : 0, Addon : 0, Prize : 242, BlindType : 202, InitialChips : 4000, RoomId : 22001, WaitingTime : 8, AddonChips : 0, MaxRebuyTimes : 0, Autoinit : 0 	}
	]


// Id
export var ChampionshipById : game.Dictionary<table.IChampionshipDefine> = {}
function readChampionshipById(){
  for(let rec of Championship) {
    ChampionshipById[rec.Id] = rec; 
  }
}
readChampionshipById();
}

