// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var Chips : table.IChipsDefine[] = [
		{ Id : 1, Phase : 1, Img : "chips_01" 	},
		{ Id : 2, Phase : 5, Img : "chips_02" 	},
		{ Id : 3, Phase : 25, Img : "chips_03" 	},
		{ Id : 4, Phase : 50, Img : "chips_04" 	},
		{ Id : 5, Phase : 100, Img : "chips_05" 	},
		{ Id : 6, Phase : 500, Img : "chips_06" 	},
		{ Id : 7, Phase : 1000, Img : "chips_07" 	},
		{ Id : 8, Phase : 5000, Img : "chips_08" 	},
		{ Id : 9, Phase : 10000, Img : "chips_09" 	},
		{ Id : 10, Phase : 50000, Img : "chips_10" 	},
		{ Id : 11, Phase : 100000, Img : "chips_11" 	},
		{ Id : 12, Phase : 500000, Img : "chips_12" 	},
		{ Id : 13, Phase : 1000000, Img : "chips_13" 	},
		{ Id : 14, Phase : 5000000, Img : "chips_14" 	},
		{ Id : 15, Phase : 10000000, Img : "chips_15" 	},
		{ Id : 16, Phase : 50000000, Img : "chips_16" 	}
	]


// Id
export var ChipsById : game.Dictionary<table.IChipsDefine> = {}
function readChipsById(){
  for(let rec of Chips) {
    ChipsById[rec.Id] = rec; 
  }
}
readChipsById();
}

