// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var GiftShop : table.IGiftShopDefine[] = [
		{ Id : 1, Type : 21, IconName : "jiubei_1", AwardId : 501, MailId : 162 	},
		{ Id : 2, Type : 21, IconName : "jiubei_2", AwardId : 502, MailId : 162 	},
		{ Id : 3, Type : 21, IconName : "jiubei_3", AwardId : 503, MailId : 162 	},
		{ Id : 4, Type : 21, IconName : "jiubei_4", AwardId : 504, MailId : 162 	},
		{ Id : 5, Type : 21, IconName : "jiubei_5", AwardId : 505, MailId : 162 	},
		{ Id : 6, Type : 22, IconName : "xiaolaba_1", AwardId : 506, MailId : 163 	},
		{ Id : 7, Type : 22, IconName : "xiaolaba_2", AwardId : 507, MailId : 163 	},
		{ Id : 8, Type : 41, IconName : "vip_3", AwardId : 508, MailId : 164 	},
		{ Id : 9, Type : 41, IconName : "vip_2", AwardId : 509, MailId : 164 	},
		{ Id : 10, Type : 41, IconName : "vip_1", AwardId : 510, MailId : 164 	}
	]


// Id
export var GiftShopById : game.Dictionary<table.IGiftShopDefine> = {}
function readGiftShopById(){
  for(let rec of GiftShop) {
    GiftShopById[rec.Id] = rec; 
  }
}
readGiftShopById();
}

