// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var GoldenBeanAward : table.IGoldenBeanAwardDefine[] = [
		{ Id : 1, AwardId : 341 	},
		{ Id : 2, AwardId : 342 	},
		{ Id : 3, AwardId : 343 	},
		{ Id : 4, AwardId : 344 	}
	]


// Id
export var GoldenBeanAwardById : game.Dictionary<table.IGoldenBeanAwardDefine> = {}
function readGoldenBeanAwardById(){
  for(let rec of GoldenBeanAward) {
    GoldenBeanAwardById[rec.Id] = rec; 
  }
}
readGoldenBeanAwardById();
}

