// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var THoleCards : table.ITHoleCardsDefine[] = [
		{ Id : 2, Type : 2, Des : "无A和K", Odds : 130 	},
		{ Id : 3, Type : 3, Des : "为同花", Odds : 200 	},
		{ Id : 4, Type : 4, Des : "含A或K", Odds : 300 	},
		{ Id : 5, Type : 5, Des : "含A", Odds : 500 	},
		{ Id : 6, Type : 6, Des : "为对子", Odds : 1500 	},
		{ Id : 7, Type : 7, Des : "为AA", Odds : 20000 	}
	]


// Id
export var THoleCardsById : game.Dictionary<table.ITHoleCardsDefine> = {}
function readTHoleCardsById(){
  for(let rec of THoleCards) {
    THoleCardsById[rec.Id] = rec; 
  }
}
readTHoleCardsById();
}

