// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var ItemBaseData : table.IItemBaseDataDefine[] = [
		{ Id : 1, Name : "金币", Type : 1, TypeDes : "数值道具", EffectType : 0, Des : "游戏中必备货币", Icon : "gold2", PileNum : 0, Extern : "" 	},
		{ Id : 2, Name : "钻石", Type : 1, TypeDes : "数值道具", EffectType : 0, Des : "钻石", Icon : "icon_zhuanshi", PileNum : 0, Extern : "" 	},
		{ Id : 3, Name : "vip经验", Type : 1, TypeDes : "数值道具", EffectType : 0, Des : "vip经验", Icon : "item_3", PileNum : 0, Extern : "" 	},
		{ Id : 4, Name : "等级经验", Type : 1, TypeDes : "数值道具", EffectType : 0, Des : "等级经验", Icon : "item_4", PileNum : 0, Extern : "" 	},
		{ Id : 5, Name : "普通VIP", Type : 1, TypeDes : "VIP", EffectType : 0, Des : "购买后立即获得专属标识、专属客服、等级加速、创建私人房、免费使用保险箱等特权", Icon : "vip_3", PileNum : 0, Extern : "" 	},
		{ Id : 6, Name : "年费VIP", Type : 1, TypeDes : "VIP", EffectType : 0, Des : "购买后立即获得专属标识、专属客服、等级加速、创建私人房、免费使用保险箱等特权。同时立即获得200点VIP成长值。", Icon : "vip_1", PileNum : 0, Extern : "" 	},
		{ Id : 7, Name : "欢乐券", Type : 1, TypeDes : "活动道具", EffectType : 0, Des : "可在欢乐送壕礼活动中使用兑换超级奖励", Icon : "", PileNum : 0, Extern : "" 	},
		{ Id : 101, Name : "10元话费赛门票", Type : 2, TypeDes : "门票", EffectType : 1, Des : "使用可免费参与10元话费赛", Icon : "item_111", PileNum : 99999, Extern : "" 	},
		{ Id : 102, Name : "100钻石赛门票", Type : 2, TypeDes : "门票", EffectType : 1, Des : "使用可免费参与100钻石赛", Icon : "item_102", PileNum : 99999, Extern : "" 	},
		{ Id : 103, Name : "100万金币欢乐赛门票", Type : 2, TypeDes : "门票", EffectType : 1, Des : "使用可免费参与100万金币欢乐赛", Icon : "item_105", PileNum : 99999, Extern : "" 	},
		{ Id : 104, Name : "免费-20万金币赛门票", Type : 2, TypeDes : "门票", EffectType : 1, Des : "使用可免费参与免费-20万金币赛", Icon : "item_104", PileNum : 99999, Extern : "" 	},
		{ Id : 105, Name : "100万金币欢乐赛门票", Type : 2, TypeDes : "门票", EffectType : 1, Des : "使用可免费参与100万金币欢乐赛", Icon : "item_105", PileNum : 99999, Extern : "" 	},
		{ Id : 106, Name : "200万金币欢乐赛门票", Type : 2, TypeDes : "门票", EffectType : 1, Des : "使用可免费参与200万金币欢乐赛", Icon : "item_106", PileNum : 99999, Extern : "" 	},
		{ Id : 107, Name : "500万金币欢乐赛门票", Type : 2, TypeDes : "门票", EffectType : 1, Des : "使用可免费参与500万金币欢乐赛", Icon : "item_107", PileNum : 99999, Extern : "" 	},
		{ Id : 108, Name : "1000万金币欢乐赛门票", Type : 2, TypeDes : "门票", EffectType : 1, Des : "使用可免费参与1000万金币欢乐赛", Icon : "item_108", PileNum : 99999, Extern : "" 	},
		{ Id : 109, Name : "2000万每日欢乐赛门票", Type : 2, TypeDes : "门票", EffectType : 1, Des : "使用可免费参与2000万每日欢乐赛", Icon : "item_109", PileNum : 99999, Extern : "" 	},
		{ Id : 110, Name : "1亿金币周赛门票", Type : 2, TypeDes : "门票", EffectType : 1, Des : "使用可免费参与1亿金币周赛", Icon : "item_110", PileNum : 99999, Extern : "" 	},
		{ Id : 111, Name : "免费-10元话费赛门票", Type : 2, TypeDes : "门票", EffectType : 1, Des : "使用可免费参与免费-10元话费赛", Icon : "item_111", PileNum : 99999, Extern : "" 	},
		{ Id : 112, Name : "30元话费争夺赛门票", Type : 2, TypeDes : "门票", EffectType : 1, Des : "使用可免费参与30元话费争夺赛", Icon : "item_112", PileNum : 99999, Extern : "" 	},
		{ Id : 113, Name : "100元话费赛门票", Type : 2, TypeDes : "门票", EffectType : 1, Des : "使用可免费参与100元话费赛", Icon : "item_113", PileNum : 99999, Extern : "" 	},
		{ Id : 201, Name : "iPhone7兑换券", Type : 3, TypeDes : "兑奖券", EffectType : 2, Des : "可兑换64GiPhone7一台，颜色随机发送", Icon : "item_201", PileNum : 99999, Extern : "锦标赛-iPhone7争霸赛冠军奖励" 	},
		{ Id : 202, Name : "iPhoneX兑换券", Type : 3, TypeDes : "兑奖券", EffectType : 2, Des : "可兑换64GiPhoneX一台，颜色随机发送", Icon : "item_202", PileNum : 99999, Extern : "活动中获得" 	},
		{ Id : 203, Name : "Ipad Pro", Type : 3, TypeDes : "兑奖券", EffectType : 2, Des : "可兑换Ipad Pro一台", Icon : "item_203", PileNum : 99999, Extern : "活动中获得" 	},
		{ Id : 204, Name : "1000元京东卡", Type : 3, TypeDes : "兑奖券", EffectType : 2, Des : "可兑换1000元京东卡一张", Icon : "item_204", PileNum : 99999, Extern : "活动中获得" 	},
		{ Id : 205, Name : "小米空气净化器", Type : 3, TypeDes : "兑奖券", EffectType : 2, Des : "可兑换小米空气净化器一台", Icon : "item_205", PileNum : 99999, Extern : "活动中获得" 	},
		{ Id : 206, Name : "500Q币", Type : 3, TypeDes : "兑奖券", EffectType : 3, Des : "可兑换500Q币", Icon : "item_206", PileNum : 99999, Extern : "活动中获得" 	},
		{ Id : 207, Name : "卡西欧电子表", Type : 3, TypeDes : "兑奖券", EffectType : 2, Des : "可兑换卡西欧电子版一个", Icon : "item_207", PileNum : 99999, Extern : "活动中获得" 	},
		{ Id : 208, Name : "300元京东卡", Type : 3, TypeDes : "兑奖券", EffectType : 2, Des : "可兑换300元京东卡", Icon : "item_208", PileNum : 99999, Extern : "活动中获得" 	},
		{ Id : 209, Name : "5Q币", Type : 3, TypeDes : "兑奖券", EffectType : 3, Des : "可兑换5Q币", Icon : "item_209", PileNum : 99999, Extern : "活动中获得" 	},
		{ Id : 210, Name : "美的电饭锅", Type : 3, TypeDes : "兑奖券", EffectType : 2, Des : "可兑换美的电饭锅一个", Icon : "item_210", PileNum : 99999, Extern : "活动中获得" 	},
		{ Id : 211, Name : "美的空调", Type : 3, TypeDes : "兑奖券", EffectType : 2, Des : "可兑换美的空调一台", Icon : "item_211", PileNum : 99999, Extern : "活动中获得" 	},
		{ Id : 212, Name : "神舟笔记本电脑", Type : 3, TypeDes : "兑奖券", EffectType : 2, Des : "可兑换神州战神K670D-G4D1笔记本电脑一台", Icon : "item_212", PileNum : 99999, Extern : "活动中获得" 	},
		{ Id : 213, Name : "iphone8 Plus", Type : 3, TypeDes : "兑奖券", EffectType : 2, Des : "可兑换iPhone8 Plus一台", Icon : "item_213", PileNum : 99999, Extern : "活动中获得" 	},
		{ Id : 214, Name : "iphone8", Type : 3, TypeDes : "兑奖券", EffectType : 2, Des : "可兑换iPhone8一台", Icon : "item_214", PileNum : 99999, Extern : "活动中获得" 	},
		{ Id : 215, Name : "OPPO R11s", Type : 3, TypeDes : "兑奖券", EffectType : 2, Des : "可兑换OPPO R11s一台", Icon : "item_215", PileNum : 99999, Extern : "活动中获得" 	},
		{ Id : 216, Name : "ZIPPO打火机", Type : 3, TypeDes : "兑奖券", EffectType : 2, Des : "可兑换ZIPPO打火机一个", Icon : "item_216", PileNum : 99999, Extern : "活动中获得" 	},
		{ Id : 217, Name : "300M全国流量", Type : 3, TypeDes : "兑奖券", EffectType : 3, Des : "可兑换300M全国流量", Icon : "item_217", PileNum : 99999, Extern : "活动中获得" 	},
		{ Id : 218, Name : "500M全国流量", Type : 3, TypeDes : "兑奖券", EffectType : 3, Des : "可兑换500M全国流量", Icon : "item_218", PileNum : 99999, Extern : "活动中获得" 	},
		{ Id : 300, Name : "5元话费兑换券", Type : 3, TypeDes : "兑奖券", EffectType : 3, Des : "可兑换5元话费", Icon : "item_300", PileNum : 99999, Extern : "通过锦标赛奖励或者活动获得的兑换券" 	},
		{ Id : 301, Name : "10元话费兑奖券", Type : 3, TypeDes : "兑奖券", EffectType : 3, Des : "可兑换10元话费", Icon : "item_301", PileNum : 99999, Extern : "通过锦标赛奖励或者活动获得的兑换券" 	},
		{ Id : 302, Name : "20元话费兑换券", Type : 3, TypeDes : "兑奖券", EffectType : 3, Des : "可兑换20元话费", Icon : "item_302", PileNum : 99999, Extern : "通过锦标赛奖励或者活动获得的兑换券" 	},
		{ Id : 303, Name : "30元话费兑换券", Type : 3, TypeDes : "兑奖券", EffectType : 3, Des : "可兑换30元话费", Icon : "item_303", PileNum : 99999, Extern : "通过锦标赛奖励或者活动获得的兑换券" 	},
		{ Id : 304, Name : "50元话费兑换券", Type : 3, TypeDes : "兑奖券", EffectType : 3, Des : "可兑换50元话费", Icon : "item_304", PileNum : 99999, Extern : "通过锦标赛奖励或者活动获得的兑换券" 	},
		{ Id : 401, Name : "小喇叭", Type : 4, TypeDes : "小喇叭", EffectType : 13, Des : "购买后可发送全服小喇叭", Icon : "item_401", PileNum : 99999, Extern : "" 	},
		{ Id : 402, Name : "金豆", Type : 4, TypeDes : "金豆", EffectType : 0, Des : "可以在兑奖界面进行兑奖", Icon : "jindou_1", PileNum : 99999, Extern : "" 	}
	]


// Id
export var ItemBaseDataById : game.Dictionary<table.IItemBaseDataDefine> = {}
function readItemBaseDataById(){
  for(let rec of ItemBaseData) {
    ItemBaseDataById[rec.Id] = rec; 
  }
}
readItemBaseDataById();
}

