// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var LoadingText : table.ILoadingTextDefine[] = [
		{ Id : 1, Desc : "永远不要像照片里的人一成不变的挂在那里，你必须综合你的行为，让对手一直在猜测你的目的。" 	},
		{ Id : 2, Desc : "只要你不是最好的牌，就要认真思索对方下重注的理由。" 	},
		{ Id : 3, Desc : "多总结下你输大钱的那些牌，比一直不停的打下去更重要。" 	},
		{ Id : 4, Desc : "你做的任何事情都有可能让你输钱——什么都不做也一样。" 	},
		{ Id : 5, Desc : "如果你有一手大牌，别忘了对手可能有一手更大的牌。" 	},
		{ Id : 6, Desc : "就算AA对27，也不是100%赢的。（所以不是无路可走的时候，最好不要起手就ALLIN）" 	},
		{ Id : 7, Desc : "那个一直弃牌的傻瓜其实是才是能一口吞掉你的巨鲨。" 	},
		{ Id : 8, Desc : "没必要花所有的筹码去验证对手是否偷鸡（万一不是你就完了）。" 	},
		{ Id : 9, Desc : "打牌不偷鸡是不行的，老是偷鸡更不是行的。" 	},
		{ Id : 10, Desc : "不要只看到偷鸡成功的，还要看到有些为了偷鸡丧命的。" 	},
		{ Id : 11, Desc : "攻击性太强的人，把自己置于乱箭之中，迟早要被穿心。" 	},
		{ Id : 12, Desc : "自己所下的注要对的起自己的底牌，即使底牌是对A,你的下注错误也会输掉一切。" 	},
		{ Id : 13, Desc : "没有什么不可能，底牌是不是好牌或坏牌，是由庄家发给的那五张牌决定的。" 	},
		{ Id : 14, Desc : "中高级场对手看牌停顿的时间能反映出一定的信息。" 	},
		{ Id : 15, Desc : "技术、胆识、运气、心态，是赢钱的关键。" 	},
		{ Id : 16, Desc : "桌上筹码最多，这样打起来轻松。不要怕别人惦记你桌上的钱。" 	},
		{ Id : 17, Desc : "拿到双A并不是你必胜的保证，有可能成为你出局的陷阱。" 	},
		{ Id : 18, Desc : "德州扑克游戏的规律就是没有任何一点规律可寻。" 	},
		{ Id : 19, Desc : "无数次的弃牌是为了一次ALLIN。" 	},
		{ Id : 20, Desc : "不要过于依赖自己的底牌，真正的底牌其实是河牌！" 	},
		{ Id : 21, Desc : "吸引对手跟重注的是彩池比例，而不是你桌上的奖金。" 	},
		{ Id : 22, Desc : "输赢无法控制，但是你可以控制输赢的多寡！" 	}
	]


// Id
export var LoadingTextById : game.Dictionary<table.ILoadingTextDefine> = {}
function readLoadingTextById(){
  for(let rec of LoadingText) {
    LoadingTextById[rec.Id] = rec; 
  }
}
readLoadingTextById();
}

