// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var Mail : table.IMailDefine[] = [
		{ Id : 101, Title : "锦标赛奖励", Type : 1, Content : "您在{0}中获得{1}，奖励{2}，请查收！" 	}
	]


// Id
export var MailById : game.Dictionary<table.IMailDefine> = {}
function readMailById(){
  for(let rec of Mail) {
    MailById[rec.Id] = rec; 
  }
}
readMailById();
}

