// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var Music : table.IMusicDefine[] = [
		{ Id : 1, Action : "allin", Des : "全下", Boy : [ "boy_allin_mp3" ], Girl : [ "girl_allin_mp3" ] 	},
		{ Id : 2, Action : "call", Des : "跟注", Boy : [ "boy_call_mp3" ], Girl : [ "girl_call_mp3" ] 	},
		{ Id : 3, Action : "check", Des : "过牌", Boy : [ "boy_check_mp3" ], Girl : [ "girl_check_mp3" ] 	},
		{ Id : 4, Action : "fold", Des : "弃牌", Boy : [ "boy_fold_mp3" ], Girl : [ "girl_fold_mp3" ] 	},
		{ Id : 5, Action : "raise", Des : "加注", Boy : [ "boy_raise_mp3" ], Girl : [ "girl_raise_mp3" ] 	},
		{ Id : 6, Action : "bet_allin", Des : "全下下注", Boy : [ "bet_allin_mp3" ], Girl : [  ] 	},
		{ Id : 7, Action : "bet_no_allin", Des : "非全下下注", Boy : [ "bet_no_allin_mp3" ], Girl : [  ] 	},
		{ Id : 8, Action : "bet_slider", Des : "加注滑动", Boy : [ "bet_slider_mp3" ], Girl : [  ] 	},
		{ Id : 9, Action : "bigWin", Des : "大胜利（葫芦及以上）", Boy : [ "bigWin_mp3" ], Girl : [  ] 	},
		{ Id : 10, Action : "blind", Des : "下盲注", Boy : [ "blind_mp3" ], Girl : [  ] 	},
		{ Id : 11, Action : "buttonClick", Des : "按钮点击", Boy : [ "buttonClick_mp3" ], Girl : [  ] 	},
		{ Id : 12, Action : "cardtype_huangjiatonghua", Des : "皇家同花顺胜利", Boy : [ "cardtype_huangjiatonghua_mp3" ], Girl : [  ] 	},
		{ Id : 13, Action : "cardtype_hulu", Des : "葫芦胜利", Boy : [ "cardtype_hulu_mp3" ], Girl : [  ] 	},
		{ Id : 14, Action : "cardtype_sitiao", Des : "四条胜利", Boy : [ "cardtype_sitiao_mp3" ], Girl : [  ] 	},
		{ Id : 15, Action : "cardtype_tonghuashun", Des : "同花顺胜利", Boy : [ "cardtype_tonghuashun_mp3" ], Girl : [  ] 	},
		{ Id : 16, Action : "chip_fall", Des : "筹码落下（一轮下注结束）", Boy : [ "chip_fall_mp3" ], Girl : [  ] 	},
		{ Id : 17, Action : "chipfly", Des : "筹码结算飞行", Boy : [ "chipfly_mp3" ], Girl : [  ] 	},
		{ Id : 18, Action : "chips_move_to_seat", Des : "结束筹码", Boy : [ "chips_move_to_seat_mp3" ], Girl : [  ] 	},
		{ Id : 19, Action : "close", Des : "界面关闭", Boy : [ "close_mp3" ], Girl : [  ] 	},
		{ Id : 20, Action : "fapai", Des : "发牌1", Boy : [ "fapai1_mp3", "fapai2_mp3" ], Girl : [  ] 	},
		{ Id : 21, Action : "foldpai", Des : "弃牌音效", Boy : [ "foldpai_mp3" ], Girl : [  ] 	},
		{ Id : 22, Action : "gift_recv", Des : "收取礼物", Boy : [ "gift_recv_mp3" ], Girl : [  ] 	},
		{ Id : 23, Action : "gift_send", Des : "发送礼物", Boy : [ "gift_send_mp3" ], Girl : [  ] 	},
		{ Id : 24, Action : "gold_fall", Des : "获得金币", Boy : [ "gold_fall_mp3" ], Girl : [  ] 	},
		{ Id : 25, Action : "hallBgm", Des : "大厅背景音乐", Boy : [ "hallBgm_mp3" ], Girl : [  ] 	},
		{ Id : 26, Action : "levelup", Des : "升级", Boy : [ "levelup_mp3" ], Girl : [  ] 	},
		{ Id : 27, Action : "light_card", Des : "亮牌1", Boy : [ "light_card1_mp3", "light_card2_mp3" ], Girl : [  ] 	},
		{ Id : 28, Action : "lose", Des : "失败", Boy : [ "lose_mp3" ], Girl : [  ] 	},
		{ Id : 29, Action : "notice", Des : "有提示（加好友、邀请入座）", Boy : [ "notice_mp3" ], Girl : [  ] 	},
		{ Id : 30, Action : "on_turn", Des : "轮到自己出牌", Boy : [ "on_turn_mp3" ], Girl : [  ] 	},
		{ Id : 31, Action : "playingBgm", Des : "游戏中背景音乐", Boy : [ "playingBgm_mp3" ], Girl : [  ] 	},
		{ Id : 32, Action : "popup", Des : "界面打开", Boy : [ "popup_mp3" ], Girl : [  ] 	},
		{ Id : 33, Action : "sentMessage", Des : "发送信息", Boy : [ "sentMessage_mp3" ], Girl : [  ] 	},
		{ Id : 34, Action : "sit", Des : "入座", Boy : [ "sit_mp3" ], Girl : [  ] 	},
		{ Id : 35, Action : "sit_out", Des : "站起", Boy : [ "sit_out_mp3" ], Girl : [  ] 	},
		{ Id : 36, Action : "sitClick", Des : "点击座位", Boy : [ "sitClick_mp3" ], Girl : [  ] 	},
		{ Id : 37, Action : "win", Des : "胜利", Boy : [ "win_mp3" ], Girl : [  ] 	},
		{ Id : 38, Action : "item_fall", Des : "获得道具", Boy : [ "item_fall_mp3" ], Girl : [  ] 	}
	]


// Id
export var MusicById : game.Dictionary<table.IMusicDefine> = {}
function readMusicById(){
  for(let rec of Music) {
    MusicById[rec.Id] = rec; 
  }
}
readMusicById();
}

