// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var Rank : table.IRankDefine[] = [
		{ Id : 1, Type : 1, Param1 : 0, Param2 : 0, Param3 : 0, Cd : 120 	},
		{ Id : 2, Type : 2, Param1 : 0, Param2 : 0, Param3 : 0, Cd : 120 	},
		{ Id : 3, Type : 3, Param1 : 0, Param2 : 0, Param3 : 0, Cd : 120 	},
		{ Id : 4, Type : 4, Param1 : 0, Param2 : 0, Param3 : 0, Cd : 120 	},
		{ Id : 5, Type : 5, Param1 : 0, Param2 : 0, Param3 : 0, Cd : 120 	},
		{ Id : 6, Type : 100, Param1 : 5, Param2 : 1, Param3 : 0, Cd : 120 	},
		{ Id : 7, Type : 100, Param1 : 5, Param2 : 2, Param3 : 0, Cd : 120 	},
		{ Id : 8, Type : 100, Param1 : 6, Param2 : 0, Param3 : 200, Cd : 120 	},
		{ Id : 9, Type : 100, Param1 : 6, Param2 : 0, Param3 : 2000, Cd : 120 	},
		{ Id : 10, Type : 100, Param1 : 6, Param2 : 0, Param3 : 20000, Cd : 120 	},
		{ Id : 11, Type : 100, Param1 : 6, Param2 : 0, Param3 : 200000, Cd : 120 	},
		{ Id : 12, Type : 100, Param1 : 6, Param2 : 1, Param3 : 200, Cd : 120 	},
		{ Id : 13, Type : 100, Param1 : 6, Param2 : 1, Param3 : 2000, Cd : 120 	},
		{ Id : 14, Type : 100, Param1 : 6, Param2 : 1, Param3 : 20000, Cd : 120 	},
		{ Id : 15, Type : 100, Param1 : 6, Param2 : 1, Param3 : 200000, Cd : 120 	}
	]


// Id
export var RankById : game.Dictionary<table.IRankDefine> = {}
function readRankById(){
  for(let rec of Rank) {
    RankById[rec.Id] = rec; 
  }
}
readRankById();
}

