// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TexasRoom : table.ITexasRoomDefine[] = [
		{ Id : 1001, Desc : "初级", Type : 1, SBlind : 10, BBlind : 20, SBuyin : 0, BBuyin : 0, Tax : 0, Seat : 0, Pattern : 0, Cd : 0, ClientCd : 0, WaitingTime : 0 	},
		{ Id : 1002, Desc : "初级", Type : 1, SBlind : 50, BBlind : 100, SBuyin : 0, BBuyin : 0, Tax : 0, Seat : 0, Pattern : 0, Cd : 0, ClientCd : 0, WaitingTime : 0 	},
		{ Id : 2001, Desc : "中级", Type : 2, SBlind : 1000, BBlind : 2000, SBuyin : 0, BBuyin : 0, Tax : 0, Seat : 0, Pattern : 0, Cd : 0, ClientCd : 0, WaitingTime : 0 	},
		{ Id : 2002, Desc : "中级", Type : 2, SBlind : 2000, BBlind : 4000, SBuyin : 0, BBuyin : 0, Tax : 0, Seat : 0, Pattern : 0, Cd : 0, ClientCd : 0, WaitingTime : 0 	},
		{ Id : 3001, Desc : "高级", Type : 3, SBlind : 10000, BBlind : 20000, SBuyin : 0, BBuyin : 0, Tax : 0, Seat : 0, Pattern : 0, Cd : 0, ClientCd : 0, WaitingTime : 0 	},
		{ Id : 3002, Desc : "高级", Type : 3, SBlind : 100000, BBlind : 200000, SBuyin : 0, BBuyin : 0, Tax : 0, Seat : 0, Pattern : 0, Cd : 0, ClientCd : 0, WaitingTime : 0 	},
		{ Id : 11001, Desc : "私人", Type : 11, SBlind : 10, BBlind : 20, SBuyin : 0, BBuyin : 0, Tax : 0, Seat : 0, Pattern : 0, Cd : 0, ClientCd : 0, WaitingTime : 0 	},
		{ Id : 11002, Desc : "私人", Type : 11, SBlind : 20, BBlind : 40, SBuyin : 0, BBuyin : 0, Tax : 0, Seat : 0, Pattern : 0, Cd : 0, ClientCd : 0, WaitingTime : 0 	},
		{ Id : 11003, Desc : "私人", Type : 11, SBlind : 100, BBlind : 200, SBuyin : 0, BBuyin : 0, Tax : 0, Seat : 0, Pattern : 0, Cd : 0, ClientCd : 0, WaitingTime : 0 	},
		{ Id : 11004, Desc : "私人", Type : 11, SBlind : 1000, BBlind : 2000, SBuyin : 0, BBuyin : 0, Tax : 0, Seat : 0, Pattern : 0, Cd : 0, ClientCd : 0, WaitingTime : 0 	}
	]


// Id
export var TexasRoomById : game.Dictionary<table.ITexasRoomDefine> = {}
function readTexasRoomById(){
  for(let rec of TexasRoom) {
    TexasRoomById[rec.Id] = rec; 
  }
}
readTexasRoomById();
}

