// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TBuildings : table.ITBuildingsDefine[] = [
		{ Id : 1001001, City : 1, Community : 1, Number : 1, MaxFloor : 10, NumPerFloor : 4, Houses1 : "2001-1000000-100", Houses2 : "3001-800000-80", Houses3 : "4001-500000-50", Houses4 : "4001-500000-50", PosX : 100, PosY : 100, Des : "1市1小区1号楼" 	},
		{ Id : 1001002, City : 1, Community : 1, Number : 2, MaxFloor : 20, NumPerFloor : 4, Houses1 : "2001-1000000-100", Houses2 : "3001-800000-80", Houses3 : "4001-500000-50", Houses4 : "4001-500000-50", PosX : 105, PosY : 105, Des : "1市1小区2号楼" 	},
		{ Id : 1002001, City : 1, Community : 2, Number : 1, MaxFloor : 10, NumPerFloor : 4, Houses1 : "2001-1000000-100", Houses2 : "3001-800000-80", Houses3 : "4001-500000-50", Houses4 : "4001-500000-50", PosX : 150, PosY : 150, Des : "1市2小区1号楼" 	},
		{ Id : 1002002, City : 1, Community : 2, Number : 2, MaxFloor : 20, NumPerFloor : 4, Houses1 : "2001-1000000-100", Houses2 : "3001-800000-80", Houses3 : "4001-500000-50", Houses4 : "4001-500000-50", PosX : 155, PosY : 155, Des : "1市2小区1号楼" 	},
		{ Id : 2001001, City : 2, Community : 1, Number : 1, MaxFloor : 10, NumPerFloor : 4, Houses1 : "2001-1000000-100", Houses2 : "3001-800000-80", Houses3 : "4001-500000-50", Houses4 : "4001-500000-50", PosX : 200, PosY : 200, Des : "2市1小区1号楼" 	}
	]


// Id
export var TBuildingsById : game.Dictionary<table.ITBuildingsDefine> = {}
function readTBuildingsById(){
  for(let rec of TBuildings) {
    TBuildingsById[rec.Id] = rec; 
  }
}
readTBuildingsById();
}

