// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TCarPartsShop : table.ITCarPartsShopDefine[] = [
	]


// Id
export var TCarPartsShopById : game.Dictionary<table.ITCarPartsShopDefine> = {}
function readTCarPartsShopById(){
  for(let rec of TCarPartsShop) {
    TCarPartsShopById[rec.Id] = rec; 
  }
}
readTCarPartsShopById();
}

