// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TCarStarAttr : table.ITCarStarAttrDefine[] = [
		{ Id : 1001, RewardInit : 0, RangeInit : 0, ItemLimitInit : 0, MoneyLimitInit : 0, SpeedInit : 0, StopTimeInit : 0, RewardAddition : 0, RangeAddition : 0, ItemLimitAddition : 0, MoneyLimitAddition : 0, SpeedAddition : 0, StopTimeAddition : 0 	}
	]


// Id
export var TCarStarAttrById : game.Dictionary<table.ITCarStarAttrDefine> = {}
function readTCarStarAttrById(){
  for(let rec of TCarStarAttr) {
    TCarStarAttrById[rec.Id] = rec; 
  }
}
readTCarStarAttrById();
}

