// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TCharacterLevel : table.ITCharacterLevelDefine[] = [
		{ Id : 1, ExpNums : 10, Reward : 1, StrengthValue : 20, HousesOwned : 1, Des : "" 	},
		{ Id : 2, ExpNums : 20, Reward : 2, StrengthValue : 20, HousesOwned : 1, Des : "" 	},
		{ Id : 3, ExpNums : 30, Reward : 3, StrengthValue : 20, HousesOwned : 1, Des : "" 	},
		{ Id : 4, ExpNums : 40, Reward : 4, StrengthValue : 20, HousesOwned : 1, Des : "" 	},
		{ Id : 5, ExpNums : 50, Reward : 5, StrengthValue : 22, HousesOwned : 2, Des : "" 	},
		{ Id : 6, ExpNums : 80, Reward : 8, StrengthValue : 25, HousesOwned : 2, Des : "" 	},
		{ Id : 7, ExpNums : 110, Reward : 11, StrengthValue : 25, HousesOwned : 2, Des : "" 	},
		{ Id : 8, ExpNums : 140, Reward : 14, StrengthValue : 25, HousesOwned : 2, Des : "" 	},
		{ Id : 9, ExpNums : 170, Reward : 17, StrengthValue : 25, HousesOwned : 2, Des : "" 	},
		{ Id : 10, ExpNums : 200, Reward : 20, StrengthValue : 30, HousesOwned : 2, Des : "" 	},
		{ Id : 11, ExpNums : 250, Reward : 25, StrengthValue : 30, HousesOwned : 2, Des : "" 	},
		{ Id : 12, ExpNums : 300, Reward : 30, StrengthValue : 30, HousesOwned : 2, Des : "" 	},
		{ Id : 13, ExpNums : 350, Reward : 35, StrengthValue : 30, HousesOwned : 2, Des : "" 	},
		{ Id : 14, ExpNums : 400, Reward : 40, StrengthValue : 30, HousesOwned : 2, Des : "" 	},
		{ Id : 15, ExpNums : 450, Reward : 45, StrengthValue : 35, HousesOwned : 3, Des : "" 	},
		{ Id : 16, ExpNums : 500, Reward : 50, StrengthValue : 35, HousesOwned : 3, Des : "" 	},
		{ Id : 17, ExpNums : 600, Reward : 60, StrengthValue : 35, HousesOwned : 3, Des : "" 	},
		{ Id : 18, ExpNums : 700, Reward : 70, StrengthValue : 35, HousesOwned : 3, Des : "" 	},
		{ Id : 19, ExpNums : 800, Reward : 80, StrengthValue : 35, HousesOwned : 3, Des : "" 	},
		{ Id : 20, ExpNums : 900, Reward : 90, StrengthValue : 40, HousesOwned : 3, Des : "" 	},
		{ Id : 21, ExpNums : 1000, Reward : 100, StrengthValue : 40, HousesOwned : 3, Des : "" 	},
		{ Id : 22, ExpNums : 1500, Reward : 150, StrengthValue : 40, HousesOwned : 3, Des : "" 	},
		{ Id : 23, ExpNums : 2000, Reward : 200, StrengthValue : 40, HousesOwned : 3, Des : "" 	},
		{ Id : 24, ExpNums : 2500, Reward : 250, StrengthValue : 40, HousesOwned : 3, Des : "" 	},
		{ Id : 25, ExpNums : 3000, Reward : 300, StrengthValue : 45, HousesOwned : 4, Des : "" 	},
		{ Id : 26, ExpNums : 3500, Reward : 350, StrengthValue : 45, HousesOwned : 4, Des : "" 	},
		{ Id : 27, ExpNums : 4000, Reward : 400, StrengthValue : 45, HousesOwned : 4, Des : "" 	},
		{ Id : 28, ExpNums : 4500, Reward : 450, StrengthValue : 45, HousesOwned : 4, Des : "" 	},
		{ Id : 29, ExpNums : 5000, Reward : 500, StrengthValue : 45, HousesOwned : 4, Des : "" 	},
		{ Id : 30, ExpNums : 6000, Reward : 600, StrengthValue : 50, HousesOwned : 4, Des : "" 	},
		{ Id : 31, ExpNums : 7000, Reward : 700, StrengthValue : 50, HousesOwned : 4, Des : "" 	},
		{ Id : 32, ExpNums : 8000, Reward : 800, StrengthValue : 50, HousesOwned : 4, Des : "" 	},
		{ Id : 33, ExpNums : 9000, Reward : 900, StrengthValue : 50, HousesOwned : 4, Des : "" 	},
		{ Id : 34, ExpNums : 10000, Reward : 1000, StrengthValue : 50, HousesOwned : 4, Des : "" 	},
		{ Id : 35, ExpNums : 11000, Reward : 1100, StrengthValue : 55, HousesOwned : 4, Des : "" 	},
		{ Id : 36, ExpNums : 12000, Reward : 1200, StrengthValue : 55, HousesOwned : 4, Des : "" 	},
		{ Id : 37, ExpNums : 13000, Reward : 1300, StrengthValue : 55, HousesOwned : 4, Des : "" 	},
		{ Id : 38, ExpNums : 14000, Reward : 1400, StrengthValue : 55, HousesOwned : 4, Des : "" 	},
		{ Id : 39, ExpNums : 15000, Reward : 1500, StrengthValue : 55, HousesOwned : 4, Des : "" 	},
		{ Id : 40, ExpNums : 16000, Reward : 1600, StrengthValue : 60, HousesOwned : 5, Des : "" 	},
		{ Id : 41, ExpNums : 17000, Reward : 1700, StrengthValue : 60, HousesOwned : 5, Des : "" 	},
		{ Id : 42, ExpNums : 18000, Reward : 1800, StrengthValue : 60, HousesOwned : 5, Des : "" 	},
		{ Id : 43, ExpNums : 19000, Reward : 1900, StrengthValue : 60, HousesOwned : 5, Des : "" 	},
		{ Id : 44, ExpNums : 20000, Reward : 2000, StrengthValue : 60, HousesOwned : 5, Des : "" 	},
		{ Id : 45, ExpNums : 21000, Reward : 2100, StrengthValue : 65, HousesOwned : 5, Des : "" 	},
		{ Id : 46, ExpNums : 22000, Reward : 2200, StrengthValue : 65, HousesOwned : 5, Des : "" 	},
		{ Id : 47, ExpNums : 23000, Reward : 2300, StrengthValue : 65, HousesOwned : 5, Des : "" 	},
		{ Id : 48, ExpNums : 24000, Reward : 2400, StrengthValue : 65, HousesOwned : 5, Des : "" 	},
		{ Id : 49, ExpNums : 25000, Reward : 2500, StrengthValue : 65, HousesOwned : 5, Des : "" 	},
		{ Id : 50, ExpNums : 0, Reward : 2500, StrengthValue : 70, HousesOwned : 6, Des : "" 	}
	]


// Id
export var TCharacterLevelById : game.Dictionary<table.ITCharacterLevelDefine> = {}
function readTCharacterLevelById(){
  for(let rec of TCharacterLevel) {
    TCharacterLevelById[rec.Id] = rec; 
  }
}
readTCharacterLevelById();
}

