// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TCitys : table.ITCitysDefine[] = [
		{ Id : 101, Type : 1, Superior : 0, Name : "北京" 	},
		{ Id : 102, Type : 1, Superior : 0, Name : "上海" 	},
		{ Id : 103, Type : 1, Superior : 0, Name : "天津" 	},
		{ Id : 104, Type : 1, Superior : 0, Name : "重庆" 	},
		{ Id : 105, Type : 1, Superior : 0, Name : "河北" 	},
		{ Id : 2001, Type : 2, Superior : 102, Name : "黄埔区" 	},
		{ Id : 2002, Type : 2, Superior : 102, Name : "徐汇区" 	},
		{ Id : 2003, Type : 2, Superior : 102, Name : "闵行区" 	},
		{ Id : 2004, Type : 2, Superior : 102, Name : "青浦区" 	},
		{ Id : 2005, Type : 2, Superior : 102, Name : "金山区" 	},
		{ Id : 2006, Type : 2, Superior : 102, Name : "静安区" 	},
		{ Id : 2007, Type : 2, Superior : 102, Name : "浦东区" 	},
		{ Id : 2008, Type : 2, Superior : 102, Name : "松江区" 	},
		{ Id : 2009, Type : 2, Superior : 102, Name : "奉贤区" 	},
		{ Id : 2010, Type : 2, Superior : 102, Name : "崇明区" 	},
		{ Id : 2011, Type : 2, Superior : 102, Name : "虹口区" 	},
		{ Id : 2012, Type : 2, Superior : 102, Name : "普陀区" 	},
		{ Id : 2013, Type : 2, Superior : 102, Name : "宝山区" 	}
	]


// Id
export var TCitysById : game.Dictionary<table.ITCitysDefine> = {}
function readTCitysById(){
  for(let rec of TCitys) {
    TCitysById[rec.Id] = rec; 
  }
}
readTCitysById();
}

