// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var Equip : table.IEquipDefine[] = [
		{ Id : 101, Name : "绅士金发", Desc : "装备获得效果", Pos : 1, SuitId : 0, Sex : 1, LoadPoint : [ "head1_1_00", "head1_1_01", "head1_1_02", "head1_1_03" ], Path : "equip_json.105", Skill : [ "1" ], Price : 20000, CoinType : 3, Suit : "boy_suit2", DebrisId : 0, DebrisNum : 0 	},
		{ Id : 102, Name : "绅士绿发", Desc : "装备获得效果", Pos : 1, SuitId : 0, Sex : 1, LoadPoint : [ "head1_1_00", "head1_1_01", "head1_1_02", "head1_1_03" ], Path : "equip_json.106", Skill : [ "6" ], Price : 10000, CoinType : 3, Suit : "boy_suit3", DebrisId : 0, DebrisNum : 0 	},
		{ Id : 103, Name : "绅士蓝发", Desc : "装备获得效果", Pos : 1, SuitId : 0, Sex : 1, LoadPoint : [ "head1_1_00", "head1_1_01", "head1_1_02", "head1_1_03" ], Path : "equip_json.107", Skill : [ "6" ], Price : 10000, CoinType : 3, Suit : "boy_suit4", DebrisId : 0, DebrisNum : 0 	},
		{ Id : 150001, Name : "少女红发", Desc : "装备获得效果", Pos : 1, SuitId : 0, Sex : 0, LoadPoint : [ "head1_1_00", "head1_1_01", "head1_1_02", "head1_1_03" ], Path : "equip_json.150001", Skill : [ "1" ], Price : 20000, CoinType : 3, Suit : "girl_suit2", DebrisId : 110001, DebrisNum : 10 	},
		{ Id : 150002, Name : "少女紫发", Desc : "装备获得效果", Pos : 1, SuitId : 0, Sex : 0, LoadPoint : [ "head1_1_00", "head1_1_01", "head1_1_02", "head1_1_03" ], Path : "equip_json.150002", Skill : [ "6" ], Price : 10000, CoinType : 3, Suit : "girl_suit3", DebrisId : 110002, DebrisNum : 10 	},
		{ Id : 150003, Name : "少女蓝发", Desc : "装备获得效果", Pos : 1, SuitId : 0, Sex : 0, LoadPoint : [ "head1_1_00", "head1_1_01", "head1_1_02", "head1_1_03" ], Path : "equip_json.150003", Skill : [ "6" ], Price : 10000, CoinType : 3, Suit : "girl_suit4", DebrisId : 110003, DebrisNum : 10 	},
		{ Id : 201, Name : "黑色迷彩卫衣", Desc : "装备获得效果", Pos : 2, SuitId : 0, Sex : 1, LoadPoint : [ "body1_1_00", "body1_1_01", "body1_1_02", "body1_1_03", "body1_1_04" ], Path : "equip_json.205", Skill : [ "2" ], Price : 20000, CoinType : 3, Suit : "boy_suit2", DebrisId : 0, DebrisNum : 0 	},
		{ Id : 202, Name : "绅士装", Desc : "装备获得效果", Pos : 2, SuitId : 0, Sex : 1, LoadPoint : [ "body1_1_00", "body1_1_01", "body1_1_02", "body1_1_03", "body1_1_04" ], Path : "equip_json.206", Skill : [ "7" ], Price : 10000, CoinType : 3, Suit : "boy_suit3", DebrisId : 0, DebrisNum : 0 	},
		{ Id : 203, Name : "水手短袖", Desc : "装备获得效果", Pos : 2, SuitId : 0, Sex : 1, LoadPoint : [ "body1_1_00", "body1_1_01", "body1_1_02", "body1_1_03", "body1_1_04" ], Path : "equip_json.207", Skill : [ "7" ], Price : 10000, CoinType : 3, Suit : "boy_suit4", DebrisId : 0, DebrisNum : 0 	},
		{ Id : 150004, Name : "星星无袖", Desc : "装备获得效果", Pos : 2, SuitId : 0, Sex : 0, LoadPoint : [ "body1_1_00", "body1_1_01", "body1_1_02", "body1_1_03", "body1_1_04" ], Path : "equip_json.150004", Skill : [ "2" ], Price : 20000, CoinType : 3, Suit : "girl_suit2", DebrisId : 110004, DebrisNum : 10 	},
		{ Id : 150005, Name : "绿色夹克", Desc : "装备获得效果", Pos : 2, SuitId : 0, Sex : 0, LoadPoint : [ "body1_1_00", "body1_1_01", "body1_1_02", "body1_1_03", "body1_1_04" ], Path : "equip_json.150005", Skill : [ "7" ], Price : 10000, CoinType : 3, Suit : "girl_suit3", DebrisId : 110005, DebrisNum : 10 	},
		{ Id : 150006, Name : "蓝色短袖", Desc : "装备获得效果", Pos : 2, SuitId : 0, Sex : 0, LoadPoint : [ "body1_1_00", "body1_1_01", "body1_1_02", "body1_1_03", "body1_1_04" ], Path : "equip_json.150006", Skill : [ "7" ], Price : 10000, CoinType : 3, Suit : "girl_suit4", DebrisId : 110006, DebrisNum : 10 	},
		{ Id : 301, Name : "军装裤", Desc : "装备获得效果", Pos : 3, SuitId : 0, Sex : 1, LoadPoint : [ "trousers1_1_00", "trousers1_1_01", "trousers1_1_02", "trousers1_1_03" ], Path : "equip_json.305", Skill : [ "3" ], Price : 20000, CoinType : 3, Suit : "boy_suit2", DebrisId : 0, DebrisNum : 0 	},
		{ Id : 302, Name : "绅士裤(绿)", Desc : "装备获得效果", Pos : 3, SuitId : 0, Sex : 1, LoadPoint : [ "trousers1_1_00", "trousers1_1_01", "trousers1_1_02", "trousers1_1_03" ], Path : "equip_json.306", Skill : [ "8" ], Price : 10000, CoinType : 3, Suit : "boy_suit3", DebrisId : 0, DebrisNum : 0 	},
		{ Id : 303, Name : "水手短裤", Desc : "装备获得效果", Pos : 3, SuitId : 0, Sex : 1, LoadPoint : [ "trousers1_1_00", "trousers1_1_01", "trousers1_1_02", "trousers1_1_03" ], Path : "equip_json.307", Skill : [ "8" ], Price : 10000, CoinType : 3, Suit : "boy_suit4", DebrisId : 0, DebrisNum : 0 	},
		{ Id : 150007, Name : "牛仔短裤", Desc : "装备获得效果", Pos : 3, SuitId : 0, Sex : 0, LoadPoint : [ "trousers1_1_00", "trousers1_1_01", "trousers1_1_02", "trousers1_1_03", "skirt1_1_00" ], Path : "equip_json.150007", Skill : [ "8" ], Price : 10000, CoinType : 3, Suit : "girl_suit4", DebrisId : 110007, DebrisNum : 10 	},
		{ Id : 150008, Name : "粉色短裙", Desc : "装备获得效果", Pos : 3, SuitId : 0, Sex : 0, LoadPoint : [ "trousers1_1_00", "trousers1_1_01", "trousers1_1_02", "trousers1_1_03", "skirt1_1_00" ], Path : "equip_json.150008", Skill : [ "8" ], Price : 10000, CoinType : 3, Suit : "girl_suit2", DebrisId : 110008, DebrisNum : 10 	},
		{ Id : 150009, Name : "灰色短裤", Desc : "装备获得效果", Pos : 3, SuitId : 0, Sex : 0, LoadPoint : [ "trousers1_1_00", "trousers1_1_01", "trousers1_1_02", "trousers1_1_03", "skirt1_1_00" ], Path : "equip_json.150009", Skill : [ "8" ], Price : 10000, CoinType : 3, Suit : "girl_suit3", DebrisId : 110009, DebrisNum : 10 	},
		{ Id : 401, Name : "白色跑鞋", Desc : "装备获得效果", Pos : 4, SuitId : 0, Sex : 1, LoadPoint : [ "shoes1_1_00", "shoes1_1_01" ], Path : "equip_json.405", Skill : [ "4" ], Price : 20000, CoinType : 3, Suit : "boy_suit2", DebrisId : 0, DebrisNum : 0 	},
		{ Id : 402, Name : "皮鞋(蓝)", Desc : "装备获得效果", Pos : 4, SuitId : 0, Sex : 1, LoadPoint : [ "shoes1_1_00", "shoes1_1_01" ], Path : "equip_json.406", Skill : [ "9" ], Price : 10000, CoinType : 3, Suit : "boy_suit3", DebrisId : 0, DebrisNum : 0 	},
		{ Id : 403, Name : "皮鞋(白)", Desc : "装备获得效果", Pos : 4, SuitId : 0, Sex : 1, LoadPoint : [ "shoes1_1_00", "shoes1_1_01" ], Path : "equip_json.407", Skill : [ "9" ], Price : 10000, CoinType : 3, Suit : "boy_suit4", DebrisId : 0, DebrisNum : 0 	},
		{ Id : 150010, Name : "小白鞋", Desc : "装备获得效果", Pos : 4, SuitId : 0, Sex : 0, LoadPoint : [ "shoes1_1_00", "shoes1_1_01" ], Path : "equip_json.150010", Skill : [ "4" ], Price : 20000, CoinType : 3, Suit : "girl_suit2", DebrisId : 110010, DebrisNum : 10 	},
		{ Id : 150011, Name : "少女鞋(黑)", Desc : "装备获得效果", Pos : 4, SuitId : 0, Sex : 0, LoadPoint : [ "shoes1_1_00", "shoes1_1_01" ], Path : "equip_json.150011", Skill : [ "9" ], Price : 10000, CoinType : 3, Suit : "girl_suit3", DebrisId : 110011, DebrisNum : 10 	},
		{ Id : 150012, Name : "少女鞋(蓝)", Desc : "装备获得效果", Pos : 4, SuitId : 0, Sex : 0, LoadPoint : [ "shoes1_1_00", "shoes1_1_01" ], Path : "equip_json.150012", Skill : [ "9" ], Price : 10000, CoinType : 3, Suit : "girl_suit4", DebrisId : 110012, DebrisNum : 10 	},
		{ Id : 501, Name : "乌鸦之翼", Desc : "装备获得效果", Pos : 5, SuitId : 0, Sex : 2, LoadPoint : [ "wing" ], Path : "equip_json.501", Skill : [ "5" ], Price : 10000, CoinType : 3, Suit : "", DebrisId : 0, DebrisNum : 0 	},
		{ Id : 502, Name : "光之翼", Desc : "装备获得效果", Pos : 5, SuitId : 0, Sex : 2, LoadPoint : [ "wing" ], Path : "equip_json.502", Skill : [ "10" ], Price : 10000, CoinType : 3, Suit : "", DebrisId : 0, DebrisNum : 0 	},
		{ Id : 503, Name : "恶魔之翼", Desc : "装备获得效果", Pos : 5, SuitId : 0, Sex : 2, LoadPoint : [ "wing" ], Path : "equip_json.503", Skill : [ "10" ], Price : 10000, CoinType : 3, Suit : "", DebrisId : 0, DebrisNum : 0 	},
		{ Id : 504, Name : "天使之翼", Desc : "装备获得效果", Pos : 5, SuitId : 0, Sex : 2, LoadPoint : [ "wing" ], Path : "equip_json.504", Skill : [ "5" ], Price : 10000, CoinType : 3, Suit : "", DebrisId : 0, DebrisNum : 0 	},
		{ Id : 601, Name : "魔术扑克", Desc : "装备获得效果", Pos : 6, SuitId : 0, Sex : 2, LoadPoint : [ "weapon" ], Path : "equip_json.601", Skill : [ "10" ], Price : 10000, CoinType : 3, Suit : "", DebrisId : 0, DebrisNum : 0 	},
		{ Id : 602, Name : "折扇", Desc : "装备获得效果", Pos : 6, SuitId : 0, Sex : 2, LoadPoint : [ "weapon" ], Path : "equip_json.602", Skill : [ "10" ], Price : 10000, CoinType : 3, Suit : "", DebrisId : 0, DebrisNum : 0 	},
		{ Id : 701, Name : "银", Desc : "装备获得效果", Pos : 7, SuitId : 0, Sex : 1, LoadPoint : [ "head1_1_00", "head1_1_01", "head1_1_02", "head1_1_03", "body1_1_00", "body1_1_01", "body1_1_02", "body1_1_03", "body1_1_04", "trousers1_1_00", "trousers1_1_01", "trousers1_1_02", "trousers1_1_03", "shoes1_1_00", "shoes1_1_01" ], Path : "equip_json.701", Skill : [ "6", "7", "8", "9", "10" ], Price : 30000, CoinType : 3, Suit : "boy_suit5", DebrisId : 0, DebrisNum : 0 	},
		{ Id : 150013, Name : "樱", Desc : "装备获得效果", Pos : 7, SuitId : 0, Sex : 0, LoadPoint : [ "head1_1_00", "head1_1_01", "head1_1_02", "head1_1_03", "body1_1_00", "body1_1_01", "body1_1_02", "body1_1_03", "body1_1_04", "trousers1_1_00", "trousers1_1_01", "trousers1_1_02", "trousers1_1_03", "shoes1_1_00", "shoes1_1_01" ], Path : "equip_json.150013", Skill : [ "6", "7", "8", "9", "10" ], Price : 30000, CoinType : 3, Suit : "girl_suit5", DebrisId : 110013, DebrisNum : 10 	},
		{ Id : 703, Name : "艾利欧", Desc : "装备获得效果", Pos : 7, SuitId : 0, Sex : 1, LoadPoint : [ "head1_1_00", "head1_1_01", "head1_1_02", "head1_1_03", "body1_1_00", "body1_1_01", "body1_1_02", "body1_1_03", "body1_1_04", "trousers1_1_00", "trousers1_1_01", "trousers1_1_02", "trousers1_1_03", "shoes1_1_00", "shoes1_1_01" ], Path : "equip_json.703", Skill : [ "6", "7", "8", "9", "10" ], Price : 30000, CoinType : 3, Suit : "boy_suit6", DebrisId : 0, DebrisNum : 0 	}
	]


// Id
export var EquipById : game.Dictionary<table.IEquipDefine> = {}
function readEquipById(){
  for(let rec of Equip) {
    EquipById[rec.Id] = rec; 
  }
}
readEquipById();
}

