// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var THouse : table.ITHouseDefine[] = [
		{ Id : 1001, ImageId : 1001, Type : 1, MaxLevel : 5, MaxCells : 4, Cells : "1-1|2-2|3-3|4-4", LevelUpCost : 50, LevelUpNeedItem : "", Des : "一居室", RoomPosition : "351-175;472-2;178-17;25-20", GirlsPosition : "368-310;230-332" 	},
		{ Id : 1002, ImageId : 1001, Type : 1, MaxLevel : 5, MaxCells : 4, Cells : "1-1|2-2|3-3|4-4", LevelUpCost : 660, LevelUpNeedItem : "", Des : "一居室", RoomPosition : "351-175;472-2;178-17;25-20", GirlsPosition : "368-310;230-332" 	},
		{ Id : 1003, ImageId : 1001, Type : 1, MaxLevel : 5, MaxCells : 4, Cells : "1-1|2-2|3-3|4-4", LevelUpCost : 2565, LevelUpNeedItem : "120004-5", Des : "一居室", RoomPosition : "351-175;472-2;178-17;25-20", GirlsPosition : "368-310;230-332" 	},
		{ Id : 1004, ImageId : 1001, Type : 1, MaxLevel : 5, MaxCells : 4, Cells : "1-1|2-2|3-3|4-4", LevelUpCost : 6500, LevelUpNeedItem : "120004-20", Des : "一居室", RoomPosition : "351-175;472-2;178-17;25-20", GirlsPosition : "368-310;230-332" 	},
		{ Id : 1005, ImageId : 1001, Type : 1, MaxLevel : 5, MaxCells : 4, Cells : "1-1|2-2|3-3|4-4", LevelUpCost : 0, LevelUpNeedItem : "120004-50", Des : "一居室", RoomPosition : "351-175;472-2;178-17;25-20", GirlsPosition : "368-310;230-332" 	},
		{ Id : 2001, ImageId : 2001, Type : 2, MaxLevel : 6, MaxCells : 5, Cells : "1-1|2-2|3-3|4-4|5-5", LevelUpCost : 75, LevelUpNeedItem : "", Des : "二居室", RoomPosition : "348-254;187-0;184-139;30-142;473-64", GirlsPosition : "360-388;604-170" 	},
		{ Id : 2002, ImageId : 2001, Type : 2, MaxLevel : 6, MaxCells : 5, Cells : "1-1|2-2|3-3|4-4|5-5", LevelUpCost : 780, LevelUpNeedItem : "", Des : "二居室", RoomPosition : "348-254;187-0;184-139;30-142;473-64", GirlsPosition : "360-388;604-170" 	},
		{ Id : 2003, ImageId : 2001, Type : 2, MaxLevel : 6, MaxCells : 5, Cells : "1-1|2-2|3-3|4-4|5-5", LevelUpCost : 2850, LevelUpNeedItem : "120004-6", Des : "二居室", RoomPosition : "348-254;187-0;184-139;30-142;473-64", GirlsPosition : "360-388;604-170" 	},
		{ Id : 2004, ImageId : 2001, Type : 2, MaxLevel : 6, MaxCells : 5, Cells : "1-1|2-2|3-3|4-4|5-5", LevelUpCost : 7020, LevelUpNeedItem : "120004-21", Des : "二居室", RoomPosition : "348-254;187-0;184-139;30-142;473-64", GirlsPosition : "360-388;604-170" 	},
		{ Id : 2005, ImageId : 2001, Type : 2, MaxLevel : 6, MaxCells : 5, Cells : "1-1|2-2|3-3|4-4|5-5", LevelUpCost : 11220, LevelUpNeedItem : "120004-51", Des : "二居室", RoomPosition : "348-254;187-0;184-139;30-142;473-64", GirlsPosition : "360-388;604-170" 	},
		{ Id : 2006, ImageId : 2001, Type : 2, MaxLevel : 6, MaxCells : 5, Cells : "1-1|2-2|3-3|4-4|5-5", LevelUpCost : 0, LevelUpNeedItem : "", Des : "二居室", RoomPosition : "348-254;187-0;184-139;30-142;473-64", GirlsPosition : "360-388;604-170" 	},
		{ Id : 3001, ImageId : 3001, Type : 3, MaxLevel : 7, MaxCells : 6, Cells : "1-1|2-2|3-3|4-4|5-5|6-6", LevelUpCost : 105, LevelUpNeedItem : "", Des : "三居室", RoomPosition : "338-367;180-64;185-238;28-253;268-0;470-150", GirlsPosition : "372-488;606-276" 	},
		{ Id : 3002, ImageId : 3001, Type : 3, MaxLevel : 7, MaxCells : 6, Cells : "1-1|2-2|3-3|4-4|5-5|6-6", LevelUpCost : 910, LevelUpNeedItem : "", Des : "三居室", RoomPosition : "338-367;180-64;185-238;28-253;268-0;470-150", GirlsPosition : "372-488;606-276" 	},
		{ Id : 3003, ImageId : 3001, Type : 3, MaxLevel : 7, MaxCells : 6, Cells : "1-1|2-2|3-3|4-4|5-5|6-6", LevelUpCost : 3150, LevelUpNeedItem : "120004-7", Des : "三居室", RoomPosition : "338-367;180-64;185-238;28-253;268-0;470-150", GirlsPosition : "372-488;606-276" 	},
		{ Id : 3004, ImageId : 3001, Type : 3, MaxLevel : 7, MaxCells : 6, Cells : "1-1|2-2|3-3|4-4|5-5|6-6", LevelUpCost : 7560, LevelUpNeedItem : "120004-22", Des : "三居室", RoomPosition : "338-367;180-64;185-238;28-253;268-0;470-150", GirlsPosition : "372-488;606-276" 	},
		{ Id : 3005, ImageId : 3001, Type : 3, MaxLevel : 7, MaxCells : 6, Cells : "1-1|2-2|3-3|4-4|5-5|6-6", LevelUpCost : 11900, LevelUpNeedItem : "120004-52", Des : "三居室", RoomPosition : "338-367;180-64;185-238;28-253;268-0;470-150", GirlsPosition : "372-488;606-276" 	},
		{ Id : 3006, ImageId : 3001, Type : 3, MaxLevel : 7, MaxCells : 6, Cells : "1-1|2-2|3-3|4-4|5-5|6-6", LevelUpCost : 17220, LevelUpNeedItem : "", Des : "三居室", RoomPosition : "338-367;180-64;185-238;28-253;268-0;470-150", GirlsPosition : "372-488;606-276" 	},
		{ Id : 3007, ImageId : 3001, Type : 3, MaxLevel : 7, MaxCells : 6, Cells : "1-1|2-2|3-3|4-4|5-5|6-6", LevelUpCost : 0, LevelUpNeedItem : "", Des : "三居室", RoomPosition : "338-367;180-64;185-238;28-253;268-0;470-150", GirlsPosition : "372-488;606-276" 	},
		{ Id : 4001, ImageId : 4001, Type : 4, MaxLevel : 8, MaxCells : 7, Cells : "1-1|2-2|3-3|4-4|5-5|6-6|7-7", LevelUpCost : 140, LevelUpNeedItem : "", Des : "四居室", RoomPosition : "338-367;180-64;185-238;28-253;268-0;470-150;496-0", GirlsPosition : "368-476;602-276" 	},
		{ Id : 4002, ImageId : 4001, Type : 4, MaxLevel : 8, MaxCells : 7, Cells : "1-1|2-2|3-3|4-4|5-5|6-6|7-7", LevelUpCost : 1050, LevelUpNeedItem : "", Des : "四居室", RoomPosition : "338-367;180-64;185-238;28-253;268-0;470-150;496-0", GirlsPosition : "368-476;602-276" 	},
		{ Id : 4003, ImageId : 4001, Type : 4, MaxLevel : 8, MaxCells : 7, Cells : "1-1|2-2|3-3|4-4|5-5|6-6|7-7", LevelUpCost : 3465, LevelUpNeedItem : "120004-8", Des : "四居室", RoomPosition : "338-367;180-64;185-238;28-253;268-0;470-150;496-0", GirlsPosition : "368-476;602-276" 	},
		{ Id : 4004, ImageId : 4001, Type : 4, MaxLevel : 8, MaxCells : 7, Cells : "1-1|2-2|3-3|4-4|5-5|6-6|7-7", LevelUpCost : 8120, LevelUpNeedItem : "120004-23", Des : "四居室", RoomPosition : "338-367;180-64;185-238;28-253;268-0;470-150;496-0", GirlsPosition : "368-476;602-276" 	},
		{ Id : 4005, ImageId : 4001, Type : 4, MaxLevel : 8, MaxCells : 7, Cells : "1-1|2-2|3-3|4-4|5-5|6-6|7-7", LevelUpCost : 12600, LevelUpNeedItem : "120004-53", Des : "四居室", RoomPosition : "338-367;180-64;185-238;28-253;268-0;470-150;496-0", GirlsPosition : "368-476;602-276" 	},
		{ Id : 4006, ImageId : 4001, Type : 4, MaxLevel : 8, MaxCells : 7, Cells : "1-1|2-2|3-3|4-4|5-5|6-6|7-7", LevelUpCost : 18060, LevelUpNeedItem : "", Des : "四居室", RoomPosition : "338-367;180-64;185-238;28-253;268-0;470-150;496-0", GirlsPosition : "368-476;602-276" 	},
		{ Id : 4007, ImageId : 4001, Type : 4, MaxLevel : 8, MaxCells : 7, Cells : "1-1|2-2|3-3|4-4|5-5|6-6|7-7", LevelUpCost : 24500, LevelUpNeedItem : "", Des : "四居室", RoomPosition : "338-367;180-64;185-238;28-253;268-0;470-150;496-0", GirlsPosition : "368-476;602-276" 	},
		{ Id : 4008, ImageId : 4001, Type : 4, MaxLevel : 8, MaxCells : 7, Cells : "1-1|2-2|3-3|4-4|5-5|6-6|7-7", LevelUpCost : 0, LevelUpNeedItem : "", Des : "四居室", RoomPosition : "338-367;180-64;185-238;28-253;268-0;470-150;496-0", GirlsPosition : "368-476;602-276" 	}
	]


// Id
export var THouseById : game.Dictionary<table.ITHouseDefine> = {}
function readTHouseById(){
  for(let rec of THouse) {
    THouseById[rec.Id] = rec; 
  }
}
readTHouseById();
}

