// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var THouseCell : table.ITHouseCellDefine[] = [
		{ Id : 1001, Type : 1, MaxLevel : 8, ProduceGold : 10, ProduceTime : 10, LevelUpCost : 50, Des : "客厅", IncomePerSecond : 1, UnlockGold : 0 	},
		{ Id : 1002, Type : 1, MaxLevel : 8, ProduceGold : 360, ProduceTime : 45, LevelUpCost : 3600, Des : "客厅", IncomePerSecond : 8, UnlockGold : 0 	},
		{ Id : 1003, Type : 1, MaxLevel : 8, ProduceGold : 1200, ProduceTime : 80, LevelUpCost : 18000, Des : "客厅", IncomePerSecond : 15, UnlockGold : 0 	},
		{ Id : 1004, Type : 1, MaxLevel : 8, ProduceGold : 2530, ProduceTime : 115, LevelUpCost : 50600, Des : "客厅", IncomePerSecond : 22, UnlockGold : 0 	},
		{ Id : 1005, Type : 1, MaxLevel : 8, ProduceGold : 4350, ProduceTime : 150, LevelUpCost : 87000, Des : "客厅", IncomePerSecond : 29, UnlockGold : 0 	},
		{ Id : 1006, Type : 1, MaxLevel : 8, ProduceGold : 6660, ProduceTime : 185, LevelUpCost : 133200, Des : "客厅", IncomePerSecond : 36, UnlockGold : 0 	},
		{ Id : 1007, Type : 1, MaxLevel : 8, ProduceGold : 9460, ProduceTime : 220, LevelUpCost : 189200, Des : "客厅", IncomePerSecond : 43, UnlockGold : 0 	},
		{ Id : 1008, Type : 1, MaxLevel : 8, ProduceGold : 12750, ProduceTime : 255, LevelUpCost : 0, Des : "客厅", IncomePerSecond : 50, UnlockGold : 0 	},
		{ Id : 2001, Type : 2, MaxLevel : 8, ProduceGold : 30, ProduceTime : 15, LevelUpCost : 150, Des : "卧室", IncomePerSecond : 2, UnlockGold : 150 	},
		{ Id : 2002, Type : 2, MaxLevel : 8, ProduceGold : 450, ProduceTime : 50, LevelUpCost : 4500, Des : "卧室", IncomePerSecond : 9, UnlockGold : 0 	},
		{ Id : 2003, Type : 2, MaxLevel : 8, ProduceGold : 1360, ProduceTime : 85, LevelUpCost : 20400, Des : "卧室", IncomePerSecond : 16, UnlockGold : 0 	},
		{ Id : 2004, Type : 2, MaxLevel : 8, ProduceGold : 2760, ProduceTime : 120, LevelUpCost : 55200, Des : "卧室", IncomePerSecond : 23, UnlockGold : 0 	},
		{ Id : 2005, Type : 2, MaxLevel : 8, ProduceGold : 4650, ProduceTime : 155, LevelUpCost : 93000, Des : "卧室", IncomePerSecond : 30, UnlockGold : 0 	},
		{ Id : 2006, Type : 2, MaxLevel : 8, ProduceGold : 7030, ProduceTime : 190, LevelUpCost : 140600, Des : "卧室", IncomePerSecond : 37, UnlockGold : 0 	},
		{ Id : 2007, Type : 2, MaxLevel : 8, ProduceGold : 9900, ProduceTime : 225, LevelUpCost : 198000, Des : "卧室", IncomePerSecond : 44, UnlockGold : 0 	},
		{ Id : 2008, Type : 2, MaxLevel : 8, ProduceGold : 13260, ProduceTime : 260, LevelUpCost : 0, Des : "卧室", IncomePerSecond : 51, UnlockGold : 0 	},
		{ Id : 3001, Type : 3, MaxLevel : 8, ProduceGold : 60, ProduceTime : 20, LevelUpCost : 300, Des : "厕所", IncomePerSecond : 3, UnlockGold : 300 	},
		{ Id : 3002, Type : 3, MaxLevel : 8, ProduceGold : 550, ProduceTime : 55, LevelUpCost : 5500, Des : "厕所", IncomePerSecond : 10, UnlockGold : 0 	},
		{ Id : 3003, Type : 3, MaxLevel : 8, ProduceGold : 1530, ProduceTime : 90, LevelUpCost : 22950, Des : "厕所", IncomePerSecond : 17, UnlockGold : 0 	},
		{ Id : 3004, Type : 3, MaxLevel : 8, ProduceGold : 3000, ProduceTime : 125, LevelUpCost : 60000, Des : "厕所", IncomePerSecond : 24, UnlockGold : 0 	},
		{ Id : 3005, Type : 3, MaxLevel : 8, ProduceGold : 4960, ProduceTime : 160, LevelUpCost : 99200, Des : "厕所", IncomePerSecond : 31, UnlockGold : 0 	},
		{ Id : 3006, Type : 3, MaxLevel : 8, ProduceGold : 7410, ProduceTime : 195, LevelUpCost : 148200, Des : "厕所", IncomePerSecond : 38, UnlockGold : 0 	},
		{ Id : 3007, Type : 3, MaxLevel : 8, ProduceGold : 10350, ProduceTime : 230, LevelUpCost : 207000, Des : "厕所", IncomePerSecond : 45, UnlockGold : 0 	},
		{ Id : 3008, Type : 3, MaxLevel : 8, ProduceGold : 13780, ProduceTime : 265, LevelUpCost : 0, Des : "厕所", IncomePerSecond : 52, UnlockGold : 0 	},
		{ Id : 4001, Type : 4, MaxLevel : 8, ProduceGold : 100, ProduceTime : 25, LevelUpCost : 500, Des : "厨房", IncomePerSecond : 4, UnlockGold : 500 	},
		{ Id : 4002, Type : 4, MaxLevel : 8, ProduceGold : 660, ProduceTime : 60, LevelUpCost : 6600, Des : "厨房", IncomePerSecond : 11, UnlockGold : 0 	},
		{ Id : 4003, Type : 4, MaxLevel : 8, ProduceGold : 1710, ProduceTime : 95, LevelUpCost : 25650, Des : "厨房", IncomePerSecond : 18, UnlockGold : 0 	},
		{ Id : 4004, Type : 4, MaxLevel : 8, ProduceGold : 3250, ProduceTime : 130, LevelUpCost : 65000, Des : "厨房", IncomePerSecond : 25, UnlockGold : 0 	},
		{ Id : 4005, Type : 4, MaxLevel : 8, ProduceGold : 5280, ProduceTime : 165, LevelUpCost : 105600, Des : "厨房", IncomePerSecond : 32, UnlockGold : 0 	},
		{ Id : 4006, Type : 4, MaxLevel : 8, ProduceGold : 7800, ProduceTime : 200, LevelUpCost : 156000, Des : "厨房", IncomePerSecond : 39, UnlockGold : 0 	},
		{ Id : 4007, Type : 4, MaxLevel : 8, ProduceGold : 10810, ProduceTime : 235, LevelUpCost : 216200, Des : "厨房", IncomePerSecond : 46, UnlockGold : 0 	},
		{ Id : 4008, Type : 4, MaxLevel : 8, ProduceGold : 14310, ProduceTime : 270, LevelUpCost : 0, Des : "厨房", IncomePerSecond : 53, UnlockGold : 0 	},
		{ Id : 5001, Type : 5, MaxLevel : 8, ProduceGold : 150, ProduceTime : 30, LevelUpCost : 750, Des : "", IncomePerSecond : 5, UnlockGold : 750 	},
		{ Id : 5002, Type : 5, MaxLevel : 8, ProduceGold : 780, ProduceTime : 65, LevelUpCost : 7800, Des : "", IncomePerSecond : 12, UnlockGold : 0 	},
		{ Id : 5003, Type : 5, MaxLevel : 8, ProduceGold : 1900, ProduceTime : 100, LevelUpCost : 28500, Des : "", IncomePerSecond : 19, UnlockGold : 0 	},
		{ Id : 5004, Type : 5, MaxLevel : 8, ProduceGold : 3510, ProduceTime : 135, LevelUpCost : 70200, Des : "", IncomePerSecond : 26, UnlockGold : 0 	},
		{ Id : 5005, Type : 5, MaxLevel : 8, ProduceGold : 5610, ProduceTime : 170, LevelUpCost : 112200, Des : "", IncomePerSecond : 33, UnlockGold : 0 	},
		{ Id : 5006, Type : 5, MaxLevel : 8, ProduceGold : 8200, ProduceTime : 205, LevelUpCost : 164000, Des : "", IncomePerSecond : 40, UnlockGold : 0 	},
		{ Id : 5007, Type : 5, MaxLevel : 8, ProduceGold : 11280, ProduceTime : 240, LevelUpCost : 225600, Des : "", IncomePerSecond : 47, UnlockGold : 0 	},
		{ Id : 5008, Type : 5, MaxLevel : 8, ProduceGold : 14850, ProduceTime : 275, LevelUpCost : 0, Des : "", IncomePerSecond : 54, UnlockGold : 0 	},
		{ Id : 6001, Type : 6, MaxLevel : 8, ProduceGold : 210, ProduceTime : 35, LevelUpCost : 1050, Des : "", IncomePerSecond : 6, UnlockGold : 1050 	},
		{ Id : 6002, Type : 6, MaxLevel : 8, ProduceGold : 910, ProduceTime : 70, LevelUpCost : 9100, Des : "", IncomePerSecond : 13, UnlockGold : 0 	},
		{ Id : 6003, Type : 6, MaxLevel : 8, ProduceGold : 2100, ProduceTime : 105, LevelUpCost : 31500, Des : "", IncomePerSecond : 20, UnlockGold : 0 	},
		{ Id : 6004, Type : 6, MaxLevel : 8, ProduceGold : 3780, ProduceTime : 140, LevelUpCost : 75600, Des : "", IncomePerSecond : 27, UnlockGold : 0 	},
		{ Id : 6005, Type : 6, MaxLevel : 8, ProduceGold : 5950, ProduceTime : 175, LevelUpCost : 119000, Des : "", IncomePerSecond : 34, UnlockGold : 0 	},
		{ Id : 6006, Type : 6, MaxLevel : 8, ProduceGold : 8610, ProduceTime : 210, LevelUpCost : 172200, Des : "", IncomePerSecond : 41, UnlockGold : 0 	},
		{ Id : 6007, Type : 6, MaxLevel : 8, ProduceGold : 11760, ProduceTime : 245, LevelUpCost : 235200, Des : "", IncomePerSecond : 48, UnlockGold : 0 	},
		{ Id : 6008, Type : 6, MaxLevel : 8, ProduceGold : 15400, ProduceTime : 280, LevelUpCost : 0, Des : "", IncomePerSecond : 55, UnlockGold : 0 	},
		{ Id : 7001, Type : 7, MaxLevel : 8, ProduceGold : 280, ProduceTime : 40, LevelUpCost : 1400, Des : "", IncomePerSecond : 7, UnlockGold : 1400 	},
		{ Id : 7002, Type : 7, MaxLevel : 8, ProduceGold : 1050, ProduceTime : 75, LevelUpCost : 10500, Des : "", IncomePerSecond : 14, UnlockGold : 0 	},
		{ Id : 7003, Type : 7, MaxLevel : 8, ProduceGold : 2310, ProduceTime : 110, LevelUpCost : 34650, Des : "", IncomePerSecond : 21, UnlockGold : 0 	},
		{ Id : 7004, Type : 7, MaxLevel : 8, ProduceGold : 4060, ProduceTime : 145, LevelUpCost : 81200, Des : "", IncomePerSecond : 28, UnlockGold : 0 	},
		{ Id : 7005, Type : 7, MaxLevel : 8, ProduceGold : 6300, ProduceTime : 180, LevelUpCost : 126000, Des : "", IncomePerSecond : 35, UnlockGold : 0 	},
		{ Id : 7006, Type : 7, MaxLevel : 8, ProduceGold : 9030, ProduceTime : 215, LevelUpCost : 180600, Des : "", IncomePerSecond : 42, UnlockGold : 0 	},
		{ Id : 7007, Type : 7, MaxLevel : 8, ProduceGold : 12250, ProduceTime : 250, LevelUpCost : 245000, Des : "", IncomePerSecond : 49, UnlockGold : 0 	},
		{ Id : 7008, Type : 7, MaxLevel : 8, ProduceGold : 15960, ProduceTime : 285, LevelUpCost : 0, Des : "", IncomePerSecond : 56, UnlockGold : 0 	}
	]


// Id
export var THouseCellById : game.Dictionary<table.ITHouseCellDefine> = {}
function readTHouseCellById(){
  for(let rec of THouseCell) {
    THouseCellById[rec.Id] = rec; 
  }
}
readTHouseCellById();
}

