// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var ItemBaseData : table.IItemBaseDataDefine[] = [
		{ Id : 1, Type : 1, Color : 1, ImageId : 10001, Name : "乳胶漆", Desc : "用于客厅，卧室升级", Clothes : 0 	},
		{ Id : 2, Type : 1, Color : 1, ImageId : 10002, Name : "木地板", Desc : "用于客厅，卧室升级", Clothes : 0 	},
		{ Id : 3, Type : 1, Color : 1, ImageId : 10003, Name : "瓷砖", Desc : "用于厨房，卫生间升级", Clothes : 0 	},
		{ Id : 4, Type : 1, Color : 1, ImageId : 10004, Name : "房屋设计图纸", Desc : "用于房屋升级", Clothes : 0 	},
		{ Id : 5, Type : 1, Color : 1, ImageId : 10005, Name : "发动机零件", Desc : "用于发动机升级", Clothes : 0 	},
		{ Id : 6, Type : 1, Color : 1, ImageId : 10006, Name : "电瓶零件", Desc : "用于电瓶升级", Clothes : 0 	},
		{ Id : 7, Type : 1, Color : 1, ImageId : 10007, Name : "后备箱零件", Desc : "用于后备箱升级", Clothes : 0 	},
		{ Id : 8, Type : 1, Color : 1, ImageId : 10008, Name : "油箱零件", Desc : "用于邮箱升级", Clothes : 0 	},
		{ Id : 9, Type : 1, Color : 1, ImageId : 10009, Name : "轮胎零件", Desc : "用于轮胎升级", Clothes : 0 	},
		{ Id : 10, Type : 1, Color : 1, ImageId : 10010, Name : "吊顶", Desc : "用于厨房，卫生间升级", Clothes : 0 	},
		{ Id : 11, Type : 1, Color : 1, ImageId : 10011, Name : "鲜花", Desc : "用于女仆升级", Clothes : 0 	},
		{ Id : 20001, Type : 2, Color : 1, ImageId : 20001, Name : "少女红发碎片", Desc : "用于少女红发合成", Clothes : 104 	},
		{ Id : 20002, Type : 2, Color : 1, ImageId : 20002, Name : "少女紫发碎片", Desc : "用于少女紫发合成", Clothes : 105 	},
		{ Id : 20003, Type : 2, Color : 1, ImageId : 20003, Name : "少女蓝发碎片", Desc : "用于少女蓝发合成", Clothes : 106 	},
		{ Id : 20004, Type : 2, Color : 1, ImageId : 20004, Name : "星星无袖碎片", Desc : "用于星星无袖合成", Clothes : 204 	},
		{ Id : 20005, Type : 2, Color : 1, ImageId : 20005, Name : "绿色夹克碎片", Desc : "用于绿色夹克合成", Clothes : 205 	},
		{ Id : 20006, Type : 2, Color : 1, ImageId : 20006, Name : "蓝色短袖碎片", Desc : "用于蓝色短袖合成", Clothes : 206 	},
		{ Id : 20007, Type : 2, Color : 1, ImageId : 20007, Name : "牛仔短裤碎片", Desc : "用于牛仔短裤合成", Clothes : 304 	},
		{ Id : 20008, Type : 2, Color : 1, ImageId : 20008, Name : "粉色短裙碎片", Desc : "用于粉色短裙合成", Clothes : 305 	},
		{ Id : 20009, Type : 2, Color : 1, ImageId : 20009, Name : "灰色短裤碎片", Desc : "用于灰色短裤合成", Clothes : 306 	},
		{ Id : 20010, Type : 2, Color : 1, ImageId : 20010, Name : "小白鞋碎片", Desc : "用于小白鞋合成", Clothes : 404 	},
		{ Id : 20011, Type : 2, Color : 1, ImageId : 20011, Name : "少女鞋(黑)碎片", Desc : "用于少女鞋(黑)合成", Clothes : 405 	},
		{ Id : 20012, Type : 2, Color : 1, ImageId : 20012, Name : "少女鞋(蓝)碎片", Desc : "用于少女鞋(蓝)合成", Clothes : 406 	},
		{ Id : 20013, Type : 2, Color : 1, ImageId : 20013, Name : "樱碎片", Desc : "用于樱碎片合成", Clothes : 702 	}
	]


// Id
export var ItemBaseDataById : game.Dictionary<table.IItemBaseDataDefine> = {}
function readItemBaseDataById(){
  for(let rec of ItemBaseData) {
    ItemBaseDataById[rec.Id] = rec; 
  }
}
readItemBaseDataById();
}

