// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TLevelMaid : table.ITLevelMaidDefine[] = [
		{ Id : 1, UpgradeID : 140001, Upgradenum : 10, ProduceGold : 7000, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 2, TakeBackCost : 1000 	},
		{ Id : 2, UpgradeID : 140001, Upgradenum : 20, ProduceGold : 7600, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 3, TakeBackCost : 1000 	},
		{ Id : 3, UpgradeID : 140001, Upgradenum : 30, ProduceGold : 8200, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 4, TakeBackCost : 1000 	},
		{ Id : 4, UpgradeID : 140001, Upgradenum : 40, ProduceGold : 8800, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 5, TakeBackCost : 1000 	},
		{ Id : 5, UpgradeID : 140001, Upgradenum : 50, ProduceGold : 9400, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 6, TakeBackCost : 1000 	},
		{ Id : 6, UpgradeID : 140001, Upgradenum : 80, ProduceGold : 10000, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 7, TakeBackCost : 1000 	},
		{ Id : 7, UpgradeID : 140001, Upgradenum : 110, ProduceGold : 10600, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 8, TakeBackCost : 1000 	},
		{ Id : 8, UpgradeID : 140001, Upgradenum : 140, ProduceGold : 11200, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 9, TakeBackCost : 1000 	},
		{ Id : 9, UpgradeID : 140001, Upgradenum : 170, ProduceGold : 11800, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 10, TakeBackCost : 1000 	},
		{ Id : 10, UpgradeID : 140001, Upgradenum : 200, ProduceGold : 12400, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 11, TakeBackCost : 1000 	},
		{ Id : 11, UpgradeID : 140001, Upgradenum : 250, ProduceGold : 13000, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 12, TakeBackCost : 1000 	},
		{ Id : 12, UpgradeID : 140001, Upgradenum : 300, ProduceGold : 13600, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 13, TakeBackCost : 1000 	},
		{ Id : 13, UpgradeID : 140001, Upgradenum : 350, ProduceGold : 14200, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 14, TakeBackCost : 1000 	},
		{ Id : 14, UpgradeID : 140001, Upgradenum : 400, ProduceGold : 14800, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 15, TakeBackCost : 1000 	},
		{ Id : 15, UpgradeID : 140001, Upgradenum : 450, ProduceGold : 15400, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 16, TakeBackCost : 1000 	},
		{ Id : 16, UpgradeID : 140001, Upgradenum : 500, ProduceGold : 16000, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 17, TakeBackCost : 1000 	},
		{ Id : 17, UpgradeID : 140001, Upgradenum : 600, ProduceGold : 16600, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 18, TakeBackCost : 1000 	},
		{ Id : 18, UpgradeID : 140001, Upgradenum : 700, ProduceGold : 17200, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 19, TakeBackCost : 1000 	},
		{ Id : 19, UpgradeID : 140001, Upgradenum : 800, ProduceGold : 17800, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 20, TakeBackCost : 1000 	},
		{ Id : 20, UpgradeID : 140001, Upgradenum : 900, ProduceGold : 18400, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 21, TakeBackCost : 1000 	},
		{ Id : 21, UpgradeID : 140001, Upgradenum : 1000, ProduceGold : 19000, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 22, TakeBackCost : 1000 	},
		{ Id : 22, UpgradeID : 140001, Upgradenum : 1500, ProduceGold : 19600, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 23, TakeBackCost : 1000 	},
		{ Id : 23, UpgradeID : 140001, Upgradenum : 2000, ProduceGold : 20200, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 24, TakeBackCost : 1000 	},
		{ Id : 24, UpgradeID : 140001, Upgradenum : 2500, ProduceGold : 20800, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 25, TakeBackCost : 1000 	},
		{ Id : 25, UpgradeID : 140001, Upgradenum : 3000, ProduceGold : 21400, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 26, TakeBackCost : 1000 	},
		{ Id : 26, UpgradeID : 140001, Upgradenum : 3500, ProduceGold : 22000, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 27, TakeBackCost : 1000 	},
		{ Id : 27, UpgradeID : 140001, Upgradenum : 4000, ProduceGold : 22600, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 28, TakeBackCost : 1000 	},
		{ Id : 28, UpgradeID : 140001, Upgradenum : 4500, ProduceGold : 23200, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 29, TakeBackCost : 1000 	},
		{ Id : 29, UpgradeID : 140001, Upgradenum : 5000, ProduceGold : 23800, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 30, TakeBackCost : 1000 	},
		{ Id : 30, UpgradeID : 140001, Upgradenum : 6000, ProduceGold : 24400, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 31, TakeBackCost : 1000 	},
		{ Id : 31, UpgradeID : 140001, Upgradenum : 7000, ProduceGold : 25000, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 32, TakeBackCost : 1000 	},
		{ Id : 32, UpgradeID : 140001, Upgradenum : 8000, ProduceGold : 25600, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 33, TakeBackCost : 1000 	},
		{ Id : 33, UpgradeID : 140001, Upgradenum : 9000, ProduceGold : 26200, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 34, TakeBackCost : 1000 	},
		{ Id : 34, UpgradeID : 140001, Upgradenum : 10000, ProduceGold : 26800, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 35, TakeBackCost : 1000 	},
		{ Id : 35, UpgradeID : 140001, Upgradenum : 11000, ProduceGold : 27400, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 36, TakeBackCost : 1000 	},
		{ Id : 36, UpgradeID : 140001, Upgradenum : 12000, ProduceGold : 28000, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 37, TakeBackCost : 1000 	},
		{ Id : 37, UpgradeID : 140001, Upgradenum : 13000, ProduceGold : 28600, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 38, TakeBackCost : 1000 	},
		{ Id : 38, UpgradeID : 140001, Upgradenum : 14000, ProduceGold : 29200, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 39, TakeBackCost : 1000 	},
		{ Id : 39, UpgradeID : 140001, Upgradenum : 15000, ProduceGold : 29800, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 40, TakeBackCost : 1000 	},
		{ Id : 40, UpgradeID : 140001, Upgradenum : 16000, ProduceGold : 30400, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 41, TakeBackCost : 1000 	},
		{ Id : 41, UpgradeID : 140001, Upgradenum : 17000, ProduceGold : 31000, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 42, TakeBackCost : 1000 	},
		{ Id : 42, UpgradeID : 140001, Upgradenum : 18000, ProduceGold : 31600, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 43, TakeBackCost : 1000 	},
		{ Id : 43, UpgradeID : 140001, Upgradenum : 19000, ProduceGold : 32200, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 44, TakeBackCost : 1000 	},
		{ Id : 44, UpgradeID : 140001, Upgradenum : 20000, ProduceGold : 32800, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 45, TakeBackCost : 1000 	},
		{ Id : 45, UpgradeID : 140001, Upgradenum : 21000, ProduceGold : 33400, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 46, TakeBackCost : 1000 	},
		{ Id : 46, UpgradeID : 140001, Upgradenum : 22000, ProduceGold : 34000, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 47, TakeBackCost : 1000 	},
		{ Id : 47, UpgradeID : 140001, Upgradenum : 23000, ProduceGold : 34600, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 48, TakeBackCost : 1000 	},
		{ Id : 48, UpgradeID : 140001, Upgradenum : 24000, ProduceGold : 35200, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 49, TakeBackCost : 1000 	},
		{ Id : 49, UpgradeID : 140001, Upgradenum : 25000, ProduceGold : 35800, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 50, TakeBackCost : 1000 	},
		{ Id : 50, UpgradeID : 140001, Upgradenum : 0, ProduceGold : 36400, ProduceTime : 3600, ProduceItem : [ "120001-1000-1", "120002-500-1", "120003-300-1", "120004-1500-1", "120005-1000-1" ], NextLevel : 0, TakeBackCost : 1000 	}
	]


// Id
export var TLevelMaidById : game.Dictionary<table.ITLevelMaidDefine> = {}
function readTLevelMaidById(){
  for(let rec of TLevelMaid) {
    TLevelMaidById[rec.Id] = rec; 
  }
}
readTLevelMaidById();
}

