// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TLevelMaid : table.ITLevelMaidDefine[] = [
		{ Id : 1, Upgrade : [ "140001", "10" ], ProduceGold : 6000, ProduceTime : 3600, NextLevel : 2 	},
		{ Id : 2, Upgrade : [ "140001", "20" ], ProduceGold : 6600, ProduceTime : 3600, NextLevel : 3 	},
		{ Id : 3, Upgrade : [ "140001", "30" ], ProduceGold : 7200, ProduceTime : 3600, NextLevel : 4 	},
		{ Id : 4, Upgrade : [ "140001", "40" ], ProduceGold : 7800, ProduceTime : 3600, NextLevel : 5 	},
		{ Id : 5, Upgrade : [ "140001", "50" ], ProduceGold : 8400, ProduceTime : 3600, NextLevel : 6 	},
		{ Id : 6, Upgrade : [ "140001", "80" ], ProduceGold : 9000, ProduceTime : 3600, NextLevel : 7 	},
		{ Id : 7, Upgrade : [ "140001", "110" ], ProduceGold : 9600, ProduceTime : 3600, NextLevel : 8 	},
		{ Id : 8, Upgrade : [ "140001", "140" ], ProduceGold : 10200, ProduceTime : 3600, NextLevel : 9 	},
		{ Id : 9, Upgrade : [ "140001", "170" ], ProduceGold : 10800, ProduceTime : 3600, NextLevel : 10 	},
		{ Id : 10, Upgrade : [ "140001", "200" ], ProduceGold : 11400, ProduceTime : 3600, NextLevel : 11 	},
		{ Id : 11, Upgrade : [ "140001", "250" ], ProduceGold : 12000, ProduceTime : 3600, NextLevel : 12 	},
		{ Id : 12, Upgrade : [ "140001", "300" ], ProduceGold : 12600, ProduceTime : 3600, NextLevel : 13 	},
		{ Id : 13, Upgrade : [ "140001", "350" ], ProduceGold : 13200, ProduceTime : 3600, NextLevel : 14 	},
		{ Id : 14, Upgrade : [ "140001", "400" ], ProduceGold : 13800, ProduceTime : 3600, NextLevel : 15 	},
		{ Id : 15, Upgrade : [ "140001", "450" ], ProduceGold : 14400, ProduceTime : 3600, NextLevel : 16 	},
		{ Id : 16, Upgrade : [ "140001", "500" ], ProduceGold : 15000, ProduceTime : 3600, NextLevel : 17 	},
		{ Id : 17, Upgrade : [ "140001", "600" ], ProduceGold : 15600, ProduceTime : 3600, NextLevel : 18 	},
		{ Id : 18, Upgrade : [ "140001", "700" ], ProduceGold : 16200, ProduceTime : 3600, NextLevel : 19 	},
		{ Id : 19, Upgrade : [ "140001", "800" ], ProduceGold : 16800, ProduceTime : 3600, NextLevel : 20 	},
		{ Id : 20, Upgrade : [ "140001", "900" ], ProduceGold : 17400, ProduceTime : 3600, NextLevel : 21 	},
		{ Id : 21, Upgrade : [ "140001", "1000" ], ProduceGold : 18000, ProduceTime : 3600, NextLevel : 22 	},
		{ Id : 22, Upgrade : [ "140001", "1500" ], ProduceGold : 18600, ProduceTime : 3600, NextLevel : 23 	},
		{ Id : 23, Upgrade : [ "140001", "2000" ], ProduceGold : 19200, ProduceTime : 3600, NextLevel : 24 	},
		{ Id : 24, Upgrade : [ "140001", "2500" ], ProduceGold : 19800, ProduceTime : 3600, NextLevel : 25 	},
		{ Id : 25, Upgrade : [ "140001", "3000" ], ProduceGold : 20400, ProduceTime : 3600, NextLevel : 26 	},
		{ Id : 26, Upgrade : [ "140001", "3500" ], ProduceGold : 21000, ProduceTime : 3600, NextLevel : 27 	},
		{ Id : 27, Upgrade : [ "140001", "4000" ], ProduceGold : 21600, ProduceTime : 3600, NextLevel : 28 	},
		{ Id : 28, Upgrade : [ "140001", "4500" ], ProduceGold : 22200, ProduceTime : 3600, NextLevel : 29 	},
		{ Id : 29, Upgrade : [ "140001", "5000" ], ProduceGold : 22800, ProduceTime : 3600, NextLevel : 30 	},
		{ Id : 30, Upgrade : [ "140001", "6000" ], ProduceGold : 23400, ProduceTime : 3600, NextLevel : 31 	},
		{ Id : 31, Upgrade : [ "140001", "7000" ], ProduceGold : 24000, ProduceTime : 3600, NextLevel : 32 	},
		{ Id : 32, Upgrade : [ "140001", "8000" ], ProduceGold : 24600, ProduceTime : 3600, NextLevel : 33 	},
		{ Id : 33, Upgrade : [ "140001", "9000" ], ProduceGold : 25200, ProduceTime : 3600, NextLevel : 34 	},
		{ Id : 34, Upgrade : [ "140001", "10000" ], ProduceGold : 25800, ProduceTime : 3600, NextLevel : 35 	},
		{ Id : 35, Upgrade : [ "140001", "11000" ], ProduceGold : 26400, ProduceTime : 3600, NextLevel : 36 	},
		{ Id : 36, Upgrade : [ "140001", "12000" ], ProduceGold : 27000, ProduceTime : 3600, NextLevel : 37 	},
		{ Id : 37, Upgrade : [ "140001", "13000" ], ProduceGold : 27600, ProduceTime : 3600, NextLevel : 38 	},
		{ Id : 38, Upgrade : [ "140001", "14000" ], ProduceGold : 28200, ProduceTime : 3600, NextLevel : 39 	},
		{ Id : 39, Upgrade : [ "140001", "15000" ], ProduceGold : 28800, ProduceTime : 3600, NextLevel : 40 	},
		{ Id : 40, Upgrade : [ "140001", "16000" ], ProduceGold : 29400, ProduceTime : 3600, NextLevel : 41 	},
		{ Id : 41, Upgrade : [ "140001", "17000" ], ProduceGold : 30000, ProduceTime : 3600, NextLevel : 42 	},
		{ Id : 42, Upgrade : [ "140001", "18000" ], ProduceGold : 30600, ProduceTime : 3600, NextLevel : 43 	},
		{ Id : 43, Upgrade : [ "140001", "19000" ], ProduceGold : 31200, ProduceTime : 3600, NextLevel : 44 	},
		{ Id : 44, Upgrade : [ "140001", "20000" ], ProduceGold : 31800, ProduceTime : 3600, NextLevel : 45 	},
		{ Id : 45, Upgrade : [ "140001", "21000" ], ProduceGold : 32400, ProduceTime : 3600, NextLevel : 46 	},
		{ Id : 46, Upgrade : [ "140001", "22000" ], ProduceGold : 33000, ProduceTime : 3600, NextLevel : 47 	},
		{ Id : 47, Upgrade : [ "140001", "23000" ], ProduceGold : 33600, ProduceTime : 3600, NextLevel : 48 	},
		{ Id : 48, Upgrade : [ "140001", "24000" ], ProduceGold : 34200, ProduceTime : 3600, NextLevel : 49 	},
		{ Id : 49, Upgrade : [ "140001", "25000" ], ProduceGold : 34800, ProduceTime : 3600, NextLevel : 50 	},
		{ Id : 50, Upgrade : [ "140001", "0" ], ProduceGold : 35400, ProduceTime : 3600, NextLevel : 0 	}
	]


// Id
export var TLevelMaidById : game.Dictionary<table.ITLevelMaidDefine> = {}
function readTLevelMaidById(){
  for(let rec of TLevelMaid) {
    TLevelMaidById[rec.Id] = rec; 
  }
}
readTLevelMaidById();
}

