// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var Equip : table.IEquipDefine[] = [
		{ Id : 101, Name : "绅士金发", Desc : "装备获得效果", Pos : 1, SuitId : 0, Sex : 1, LoadPoint : [ "head1_1_00", "head1_1_01", "head1_1_02", "head1_1_03" ], Path : "equip_json.105", Skill : [ "1" ], Price : 20000, CoinType : 1, Suit : "boy_suit2" 	},
		{ Id : 102, Name : "绅士绿发", Desc : "装备获得效果", Pos : 1, SuitId : 0, Sex : 1, LoadPoint : [ "head1_1_00", "head1_1_01", "head1_1_02", "head1_1_03" ], Path : "equip_json.106", Skill : [ "6" ], Price : 10000, CoinType : 2, Suit : "boy_suit3" 	},
		{ Id : 103, Name : "绅士蓝发", Desc : "装备获得效果", Pos : 1, SuitId : 0, Sex : 1, LoadPoint : [ "head1_1_00", "head1_1_01", "head1_1_02", "head1_1_03" ], Path : "equip_json.107", Skill : [ "6" ], Price : 10000, CoinType : 2, Suit : "boy_suit4" 	},
		{ Id : 104, Name : "少女橘发", Desc : "装备获得效果", Pos : 1, SuitId : 0, Sex : 0, LoadPoint : [ "head1_1_00", "head1_1_01", "head1_1_02", "head1_1_03" ], Path : "equip_json.108", Skill : [ "1" ], Price : 20000, CoinType : 1, Suit : "girl_suit2" 	},
		{ Id : 105, Name : "少女紫发", Desc : "装备获得效果", Pos : 1, SuitId : 0, Sex : 0, LoadPoint : [ "head1_1_00", "head1_1_01", "head1_1_02", "head1_1_03" ], Path : "equip_json.109", Skill : [ "6" ], Price : 10000, CoinType : 2, Suit : "girl_suit3" 	},
		{ Id : 106, Name : "少女蓝发", Desc : "装备获得效果", Pos : 1, SuitId : 0, Sex : 0, LoadPoint : [ "head1_1_00", "head1_1_01", "head1_1_02", "head1_1_03" ], Path : "equip_json.110", Skill : [ "6" ], Price : 10000, CoinType : 2, Suit : "girl_suit4" 	},
		{ Id : 201, Name : "黑色迷彩卫衣", Desc : "装备获得效果", Pos : 2, SuitId : 0, Sex : 1, LoadPoint : [ "body1_1_00", "body1_1_01", "body1_1_02", "body1_1_03", "body1_1_04" ], Path : "equip_json.205", Skill : [ "2" ], Price : 20000, CoinType : 1, Suit : "boy_suit2" 	},
		{ Id : 202, Name : "绅士装", Desc : "装备获得效果", Pos : 2, SuitId : 0, Sex : 1, LoadPoint : [ "body1_1_00", "body1_1_01", "body1_1_02", "body1_1_03", "body1_1_04" ], Path : "equip_json.206", Skill : [ "7" ], Price : 10000, CoinType : 2, Suit : "boy_suit3" 	},
		{ Id : 203, Name : "水手短袖", Desc : "装备获得效果", Pos : 2, SuitId : 0, Sex : 1, LoadPoint : [ "body1_1_00", "body1_1_01", "body1_1_02", "body1_1_03", "body1_1_04" ], Path : "equip_json.207", Skill : [ "7" ], Price : 10000, CoinType : 2, Suit : "boy_suit4" 	},
		{ Id : 204, Name : "星星无袖", Desc : "装备获得效果", Pos : 2, SuitId : 0, Sex : 0, LoadPoint : [ "body1_1_00", "body1_1_01", "body1_1_02", "body1_1_03", "body1_1_04" ], Path : "equip_json.208", Skill : [ "2" ], Price : 20000, CoinType : 1, Suit : "girl_suit2" 	},
		{ Id : 205, Name : "绿色夹克", Desc : "装备获得效果", Pos : 2, SuitId : 0, Sex : 0, LoadPoint : [ "body1_1_00", "body1_1_01", "body1_1_02", "body1_1_03", "body1_1_04" ], Path : "equip_json.209", Skill : [ "7" ], Price : 10000, CoinType : 2, Suit : "girl_suit3" 	},
		{ Id : 206, Name : "蓝色短袖", Desc : "装备获得效果", Pos : 2, SuitId : 0, Sex : 0, LoadPoint : [ "body1_1_00", "body1_1_01", "body1_1_02", "body1_1_03", "body1_1_04" ], Path : "equip_json.210", Skill : [ "7" ], Price : 10000, CoinType : 2, Suit : "girl_suit4" 	},
		{ Id : 301, Name : "军装裤", Desc : "装备获得效果", Pos : 3, SuitId : 0, Sex : 1, LoadPoint : [ "trousers1_1_00", "trousers1_1_01", "trousers1_1_02", "trousers1_1_03" ], Path : "equip_json.305", Skill : [ "3" ], Price : 20000, CoinType : 1, Suit : "boy_suit2" 	},
		{ Id : 302, Name : "绅士裤(绿)", Desc : "装备获得效果", Pos : 3, SuitId : 0, Sex : 1, LoadPoint : [ "trousers1_1_00", "trousers1_1_01", "trousers1_1_02", "trousers1_1_03" ], Path : "equip_json.306", Skill : [ "8" ], Price : 10000, CoinType : 2, Suit : "boy_suit3" 	},
		{ Id : 303, Name : "水手短裤", Desc : "装备获得效果", Pos : 3, SuitId : 0, Sex : 1, LoadPoint : [ "trousers1_1_00", "trousers1_1_01", "trousers1_1_02", "trousers1_1_03" ], Path : "equip_json.307", Skill : [ "8" ], Price : 10000, CoinType : 2, Suit : "boy_suit4" 	},
		{ Id : 304, Name : "牛仔短裤", Desc : "装备获得效果", Pos : 3, SuitId : 0, Sex : 0, LoadPoint : [ "trousers1_1_00", "trousers1_1_01", "trousers1_1_02", "trousers1_1_03", "skirt1_1_00" ], Path : "equip_json.308", Skill : [ "8" ], Price : 10000, CoinType : 2, Suit : "girl_suit4" 	},
		{ Id : 305, Name : "粉色短裙", Desc : "装备获得效果", Pos : 3, SuitId : 0, Sex : 0, LoadPoint : [ "trousers1_1_00", "trousers1_1_01", "trousers1_1_02", "trousers1_1_03", "skirt1_1_00" ], Path : "equip_json.309", Skill : [ "8" ], Price : 10000, CoinType : 2, Suit : "girl_suit2" 	},
		{ Id : 306, Name : "灰色短裤", Desc : "装备获得效果", Pos : 3, SuitId : 0, Sex : 0, LoadPoint : [ "trousers1_1_00", "trousers1_1_01", "trousers1_1_02", "trousers1_1_03", "skirt1_1_00" ], Path : "equip_json.310", Skill : [ "8" ], Price : 10000, CoinType : 2, Suit : "girl_suit3" 	},
		{ Id : 401, Name : "白色跑鞋", Desc : "装备获得效果", Pos : 4, SuitId : 0, Sex : 1, LoadPoint : [ "shoes1_1_00", "shoes1_1_01" ], Path : "equip_json.405", Skill : [ "4" ], Price : 20000, CoinType : 1, Suit : "boy_suit2" 	},
		{ Id : 402, Name : "皮鞋(蓝)", Desc : "装备获得效果", Pos : 4, SuitId : 0, Sex : 1, LoadPoint : [ "shoes1_1_00", "shoes1_1_01" ], Path : "equip_json.406", Skill : [ "9" ], Price : 10000, CoinType : 2, Suit : "boy_suit3" 	},
		{ Id : 403, Name : "皮鞋(白)", Desc : "装备获得效果", Pos : 4, SuitId : 0, Sex : 1, LoadPoint : [ "shoes1_1_00", "shoes1_1_01" ], Path : "equip_json.407", Skill : [ "9" ], Price : 10000, CoinType : 2, Suit : "boy_suit4" 	},
		{ Id : 404, Name : "小白鞋", Desc : "装备获得效果", Pos : 4, SuitId : 0, Sex : 0, LoadPoint : [ "shoes1_1_00", "shoes1_1_01" ], Path : "equip_json.408", Skill : [ "4" ], Price : 20000, CoinType : 1, Suit : "girl_suit2" 	},
		{ Id : 405, Name : "少女鞋(黑)", Desc : "装备获得效果", Pos : 4, SuitId : 0, Sex : 0, LoadPoint : [ "shoes1_1_00", "shoes1_1_01" ], Path : "equip_json.409", Skill : [ "9" ], Price : 10000, CoinType : 2, Suit : "girl_suit3" 	},
		{ Id : 406, Name : "少女鞋(蓝)", Desc : "装备获得效果", Pos : 4, SuitId : 0, Sex : 0, LoadPoint : [ "shoes1_1_00", "shoes1_1_01" ], Path : "equip_json.410", Skill : [ "9" ], Price : 10000, CoinType : 2, Suit : "girl_suit4" 	},
		{ Id : 501, Name : "乌鸦之翼", Desc : "装备获得效果", Pos : 5, SuitId : 0, Sex : 2, LoadPoint : [ "wing" ], Path : "equip_json.501", Skill : [ "5" ], Price : 10000, CoinType : 2, Suit : "" 	},
		{ Id : 502, Name : "光之翼", Desc : "装备获得效果", Pos : 5, SuitId : 0, Sex : 2, LoadPoint : [ "wing" ], Path : "equip_json.502", Skill : [ "10" ], Price : 10000, CoinType : 2, Suit : "" 	},
		{ Id : 503, Name : "恶魔之翼", Desc : "装备获得效果", Pos : 5, SuitId : 0, Sex : 2, LoadPoint : [ "wing" ], Path : "equip_json.503", Skill : [ "10" ], Price : 10000, CoinType : 2, Suit : "" 	},
		{ Id : 504, Name : "天使之翼", Desc : "装备获得效果", Pos : 5, SuitId : 0, Sex : 2, LoadPoint : [ "wing" ], Path : "equip_json.504", Skill : [ "5" ], Price : 10000, CoinType : 2, Suit : "" 	},
		{ Id : 601, Name : "魔术扑克", Desc : "装备获得效果", Pos : 6, SuitId : 0, Sex : 2, LoadPoint : [ "weapon" ], Path : "equip_json.601", Skill : [ "10" ], Price : 10000, CoinType : 2, Suit : "" 	},
		{ Id : 602, Name : "折扇", Desc : "装备获得效果", Pos : 6, SuitId : 0, Sex : 2, LoadPoint : [ "weapon" ], Path : "equip_json.602", Skill : [ "10" ], Price : 10000, CoinType : 2, Suit : "" 	},
		{ Id : 701, Name : "银", Desc : "装备获得效果", Pos : 7, SuitId : 0, Sex : 1, LoadPoint : [ "head1_1_00", "head1_1_01", "head1_1_02", "head1_1_03", "body1_1_00", "body1_1_01", "body1_1_02", "body1_1_03", "body1_1_04", "trousers1_1_00", "trousers1_1_01", "trousers1_1_02", "trousers1_1_03", "shoes1_1_00", "shoes1_1_01" ], Path : "equip_json.701", Skill : [ "6", "7", "8", "9", "10" ], Price : 30000, CoinType : 2, Suit : "boy_suit5" 	},
		{ Id : 702, Name : "樱", Desc : "装备获得效果", Pos : 7, SuitId : 0, Sex : 0, LoadPoint : [ "head1_1_00", "head1_1_01", "head1_1_02", "head1_1_03", "body1_1_00", "body1_1_01", "body1_1_02", "body1_1_03", "body1_1_04", "trousers1_1_00", "trousers1_1_01", "trousers1_1_02", "trousers1_1_03", "shoes1_1_00", "shoes1_1_01" ], Path : "equip_json.702", Skill : [ "6", "7", "8", "9", "10" ], Price : 30000, CoinType : 2, Suit : "girl_suit5" 	},
		{ Id : 703, Name : "艾利欧", Desc : "装备获得效果", Pos : 7, SuitId : 0, Sex : 1, LoadPoint : [ "head1_1_00", "head1_1_01", "head1_1_02", "head1_1_03", "body1_1_00", "body1_1_01", "body1_1_02", "body1_1_03", "body1_1_04", "trousers1_1_00", "trousers1_1_01", "trousers1_1_02", "trousers1_1_03", "shoes1_1_00", "shoes1_1_01" ], Path : "equip_json.703", Skill : [ "6", "7", "8", "9", "10" ], Price : 30000, CoinType : 2, Suit : "boy_suit6" 	}
	]


// Id
export var EquipById : game.Dictionary<table.IEquipDefine> = {}
function readEquipById(){
  for(let rec of Equip) {
    EquipById[rec.Id] = rec; 
  }
}
readEquipById();
}

