// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var Equip : table.IEquipDefine[] = [
		{ Id : 101, Name : "头盔", Desc : "装备获得效果", Pos : 1, SuitId : 0, Sex : 1, LoadPoint : [ "trousers1_1_00", "trousers1_1_01", "trousers1_1_02", "trousers1_1_03", "trousers1_1_04" ], Path : "equip_json.101", Skill : [ "1", "2" ], Price : 10, CoinType : 1 	},
		{ Id : 102, Name : "头盔", Desc : "装备获得效果", Pos : 1, SuitId : 0, Sex : 0, LoadPoint : [  ], Path : "equip_json.102", Skill : [ "1", "2" ], Price : 10, CoinType : 1 	},
		{ Id : 103, Name : "头盔", Desc : "装备获得效果", Pos : 1, SuitId : 0, Sex : 0, LoadPoint : [  ], Path : "equip_json.103", Skill : [ "1", "2" ], Price : 10, CoinType : 1 	},
		{ Id : 104, Name : "头盔", Desc : "装备获得效果", Pos : 1, SuitId : 0, Sex : 0, LoadPoint : [  ], Path : "equip_json.104", Skill : [ "1", "2" ], Price : 10, CoinType : 1 	},
		{ Id : 201, Name : "上衣", Desc : "装备获得效果", Pos : 2, SuitId : 0, Sex : 1, LoadPoint : [ "trousers1_1_00", "trousers1_1_01", "trousers1_1_02", "trousers1_1_03", "trousers1_1_04", "trousers1_1_05", "trousers1_1_06" ], Path : "equip_json.201", Skill : [ "1", "3" ], Price : 10, CoinType : 1 	},
		{ Id : 202, Name : "上衣", Desc : "装备获得效果", Pos : 2, SuitId : 0, Sex : 0, LoadPoint : [  ], Path : "equip_json.202", Skill : [ "1", "3" ], Price : 10, CoinType : 1 	},
		{ Id : 203, Name : "上衣", Desc : "装备获得效果", Pos : 2, SuitId : 0, Sex : 0, LoadPoint : [  ], Path : "equip_json.203", Skill : [ "1", "3" ], Price : 10, CoinType : 1 	},
		{ Id : 204, Name : "上衣", Desc : "装备获得效果", Pos : 2, SuitId : 0, Sex : 0, LoadPoint : [  ], Path : "equip_json.204", Skill : [ "1", "3" ], Price : 10, CoinType : 1 	},
		{ Id : 301, Name : "裤子", Desc : "装备获得效果", Pos : 3, SuitId : 0, Sex : 1, LoadPoint : [ "trousers1_1_00", "trousers1_1_01", "trousers1_1_02", "trousers1_1_03", "trousers1_1_04", "trousers1_1_05", "trousers1_1_06" ], Path : "equip_json.301", Skill : [ "1", "4" ], Price : 10, CoinType : 1 	},
		{ Id : 302, Name : "裤子", Desc : "装备获得效果", Pos : 3, SuitId : 0, Sex : 0, LoadPoint : [  ], Path : "equip_json.302", Skill : [ "1", "4" ], Price : 10, CoinType : 1 	},
		{ Id : 303, Name : "裤子", Desc : "装备获得效果", Pos : 3, SuitId : 0, Sex : 1, LoadPoint : [  ], Path : "equip_json.303", Skill : [ "1", "4" ], Price : 10, CoinType : 1 	},
		{ Id : 304, Name : "裤子", Desc : "装备获得效果", Pos : 3, SuitId : 0, Sex : 0, LoadPoint : [  ], Path : "equip_json.304", Skill : [ "1", "4" ], Price : 10, CoinType : 1 	},
		{ Id : 401, Name : "鞋子", Desc : "装备获得效果", Pos : 4, SuitId : 0, Sex : 1, LoadPoint : [  ], Path : "equip_json.401", Skill : [ "1", "5" ], Price : 10, CoinType : 1 	},
		{ Id : 402, Name : "鞋子", Desc : "装备获得效果", Pos : 4, SuitId : 0, Sex : 0, LoadPoint : [  ], Path : "equip_json.402", Skill : [ "1", "5" ], Price : 10, CoinType : 1 	},
		{ Id : 403, Name : "鞋子", Desc : "装备获得效果", Pos : 4, SuitId : 0, Sex : 1, LoadPoint : [  ], Path : "equip_json.403", Skill : [ "1", "5" ], Price : 10, CoinType : 1 	},
		{ Id : 404, Name : "鞋子", Desc : "装备获得效果", Pos : 4, SuitId : 0, Sex : 0, LoadPoint : [  ], Path : "equip_json.404", Skill : [ "1", "5" ], Price : 10, CoinType : 1 	},
		{ Id : 501, Name : "翅膀", Desc : "装备获得效果", Pos : 5, SuitId : 0, Sex : 2, LoadPoint : [  ], Path : "equip_json.501", Skill : [ "1", "6" ], Price : 10, CoinType : 1 	},
		{ Id : 502, Name : "翅膀", Desc : "装备获得效果", Pos : 5, SuitId : 0, Sex : 0, LoadPoint : [  ], Path : "equip_json.502", Skill : [ "1", "6" ], Price : 10, CoinType : 1 	},
		{ Id : 503, Name : "翅膀", Desc : "装备获得效果", Pos : 5, SuitId : 0, Sex : 2, LoadPoint : [  ], Path : "equip_json.503", Skill : [ "1", "6" ], Price : 10, CoinType : 1 	},
		{ Id : 504, Name : "翅膀", Desc : "装备获得效果", Pos : 5, SuitId : 0, Sex : 0, LoadPoint : [  ], Path : "equip_json.504", Skill : [ "1", "6" ], Price : 10, CoinType : 1 	},
		{ Id : 601, Name : "棒棒", Desc : "装备获得效果", Pos : 6, SuitId : 0, Sex : 2, LoadPoint : [  ], Path : "equip_json.601", Skill : [ "1", "7" ], Price : 10, CoinType : 1 	},
		{ Id : 602, Name : "棒棒", Desc : "装备获得效果", Pos : 6, SuitId : 0, Sex : 0, LoadPoint : [  ], Path : "equip_json.602", Skill : [ "1", "7" ], Price : 10, CoinType : 1 	},
		{ Id : 603, Name : "棒棒", Desc : "装备获得效果", Pos : 6, SuitId : 0, Sex : 2, LoadPoint : [  ], Path : "equip_json.603", Skill : [ "1", "7" ], Price : 10, CoinType : 1 	},
		{ Id : 604, Name : "棒棒", Desc : "装备获得效果", Pos : 6, SuitId : 0, Sex : 0, LoadPoint : [  ], Path : "equip_json.604", Skill : [ "1", "7" ], Price : 10, CoinType : 1 	},
		{ Id : 701, Name : "套装1", Desc : "装备获得效果", Pos : 7, SuitId : 0, Sex : 0, LoadPoint : [  ], Path : "equip_json.701", Skill : [ "1", "8" ], Price : 10, CoinType : 1 	},
		{ Id : 702, Name : "套装2", Desc : "装备获得效果", Pos : 7, SuitId : 0, Sex : 0, LoadPoint : [  ], Path : "equip_json.702", Skill : [ "1", "8" ], Price : 10, CoinType : 1 	},
		{ Id : 703, Name : "套装3", Desc : "装备获得效果", Pos : 7, SuitId : 0, Sex : 0, LoadPoint : [  ], Path : "equip_json.703", Skill : [ "1", "8" ], Price : 10, CoinType : 1 	},
		{ Id : 704, Name : "套装4", Desc : "装备获得效果", Pos : 7, SuitId : 0, Sex : 0, LoadPoint : [  ], Path : "equip_json.704", Skill : [ "1", "8" ], Price : 10, CoinType : 1 	}
	]


// Id
export var EquipById : game.Dictionary<table.IEquipDefine> = {}
function readEquipById(){
  for(let rec of Equip) {
    EquipById[rec.Id] = rec; 
  }
}
readEquipById();
}

