// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var Activity_bankruptSubsidy : table.IActivity_bankruptSubsidyDefine[] = [
		{ Id : 1, ActivityId : 7, SubId : 1, AwardId : 61001, LimitGold : 1000, Times : 4 	}
	]


// Id
export var Activity_bankruptSubsidyById : game.Dictionary<table.IActivity_bankruptSubsidyDefine> = {}
function readActivity_bankruptSubsidyById(){
  for(let rec of Activity_bankruptSubsidy) {
    Activity_bankruptSubsidyById[rec.Id] = rec; 
  }
}
readActivity_bankruptSubsidyById();
}

