// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TCar : table.ITCarDefine[] = [
		{ Id : 1001, Brand : "奔驰", Model : "smart", MoveRange : 1000, Capacity : 1200, RewardPerH : 120, Price : 2400, Des : "", path : "carIconAltas_json.small_1", bigpath : "carIconAltas_json.big_1" 	},
		{ Id : 1002, Brand : "宝马", Model : "mini", MoveRange : 1500, Capacity : 12000, RewardPerH : 600, Price : 24000, Des : "", path : "carIconAltas_json.small_2", bigpath : "carIconAltas_json.big_2" 	},
		{ Id : 1003, Brand : "雪佛莱", Model : "科迈罗", MoveRange : 2000, Capacity : 27000, RewardPerH : 900, Price : 54000, Des : "", path : "carIconAltas_json.small_3", bigpath : "carIconAltas_json.big_3" 	},
		{ Id : 1004, Brand : "保时捷", Model : "911", MoveRange : 2500, Capacity : 72000, RewardPerH : 1200, Price : 96000, Des : "", path : "carIconAltas_json.small_4", bigpath : "carIconAltas_json.big_4" 	},
		{ Id : 1005, Brand : "奔驰", Model : "G级", MoveRange : 3000, Capacity : 180000, RewardPerH : 1500, Price : 150000, Des : "", path : "carIconAltas_json.small_5", bigpath : "carIconAltas_json.big_5" 	},
		{ Id : 1006, Brand : "劳斯劳斯", Model : "古斯特", MoveRange : 4000, Capacity : 324000, RewardPerH : 1800, Price : 216000, Des : "", path : "carIconAltas_json.small_6", bigpath : "carIconAltas_json.big_6" 	}
	]


// Id
export var TCarById : game.Dictionary<table.ITCarDefine> = {}
function readTCarById(){
  for(let rec of TCar) {
    TCarById[rec.Id] = rec; 
  }
}
readTCarById();
}

