// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TCarModel : table.ITCarModelDefine[] = [
		{ Id : 1001, Model : "smart" 	},
		{ Id : 2001, Model : "思域" 	},
		{ Id : 3001, Model : "polo" 	},
		{ Id : 4001, Model : "汉兰达" 	},
		{ Id : 5001, Model : "A4L" 	},
		{ Id : 6001, Model : "mini" 	},
		{ Id : 7001, Model : "科迈罗" 	},
		{ Id : 8001, Model : "911" 	},
		{ Id : 9001, Model : "G系列" 	},
		{ Id : 10001, Model : "古斯特" 	}
	]


// Id
export var TCarModelById : game.Dictionary<table.ITCarModelDefine> = {}
function readTCarModelById(){
  for(let rec of TCarModel) {
    TCarModelById[rec.Id] = rec; 
  }
}
readTCarModelById();
}

