// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TCarPartLevelup : table.ITCarPartLevelupDefine[] = [
		{ Id : 1, Partid : 1001, Level : 1, Exp : 1000, Cost : 1000 	},
		{ Id : 2, Partid : 1002, Level : 2, Exp : 1500, Cost : 2000 	},
		{ Id : 3, Partid : 1003, Level : 3, Exp : 2000, Cost : 3000 	},
		{ Id : 4, Partid : 1004, Level : 4, Exp : 2500, Cost : 4000 	},
		{ Id : 5, Partid : 1005, Level : 5, Exp : 3000, Cost : 5000 	},
		{ Id : 6, Partid : 1006, Level : 6, Exp : 3500, Cost : 6000 	},
		{ Id : 7, Partid : 1007, Level : 7, Exp : 4000, Cost : 7000 	},
		{ Id : 8, Partid : 1008, Level : 8, Exp : 4500, Cost : 8000 	},
		{ Id : 9, Partid : 1009, Level : 9, Exp : 5000, Cost : 9000 	},
		{ Id : 10, Partid : 1010, Level : 10, Exp : 5500, Cost : 10000 	},
		{ Id : 11, Partid : 2001, Level : 1, Exp : 1000, Cost : 1000 	},
		{ Id : 12, Partid : 2002, Level : 2, Exp : 1500, Cost : 2000 	},
		{ Id : 13, Partid : 2003, Level : 3, Exp : 2000, Cost : 3000 	},
		{ Id : 14, Partid : 2004, Level : 4, Exp : 2500, Cost : 4000 	},
		{ Id : 15, Partid : 2005, Level : 5, Exp : 3000, Cost : 5000 	},
		{ Id : 16, Partid : 2006, Level : 6, Exp : 3500, Cost : 6000 	},
		{ Id : 17, Partid : 2007, Level : 7, Exp : 4000, Cost : 7000 	},
		{ Id : 18, Partid : 2008, Level : 8, Exp : 4500, Cost : 8000 	},
		{ Id : 19, Partid : 2009, Level : 9, Exp : 5000, Cost : 9000 	},
		{ Id : 20, Partid : 2010, Level : 10, Exp : 5500, Cost : 10000 	},
		{ Id : 21, Partid : 3001, Level : 1, Exp : 1000, Cost : 1000 	},
		{ Id : 22, Partid : 3002, Level : 2, Exp : 1500, Cost : 2000 	},
		{ Id : 23, Partid : 3003, Level : 3, Exp : 2000, Cost : 3000 	},
		{ Id : 24, Partid : 3004, Level : 4, Exp : 2500, Cost : 4000 	},
		{ Id : 25, Partid : 3005, Level : 5, Exp : 3000, Cost : 5000 	},
		{ Id : 26, Partid : 3006, Level : 6, Exp : 3500, Cost : 6000 	},
		{ Id : 27, Partid : 3007, Level : 7, Exp : 4000, Cost : 7000 	},
		{ Id : 28, Partid : 3008, Level : 8, Exp : 4500, Cost : 8000 	},
		{ Id : 29, Partid : 3009, Level : 9, Exp : 5000, Cost : 9000 	},
		{ Id : 30, Partid : 3010, Level : 10, Exp : 5500, Cost : 10000 	},
		{ Id : 31, Partid : 4001, Level : 1, Exp : 1000, Cost : 1000 	},
		{ Id : 32, Partid : 4002, Level : 2, Exp : 1500, Cost : 2000 	},
		{ Id : 33, Partid : 4003, Level : 3, Exp : 2000, Cost : 3000 	},
		{ Id : 34, Partid : 4004, Level : 4, Exp : 2500, Cost : 4000 	},
		{ Id : 35, Partid : 4005, Level : 5, Exp : 3000, Cost : 5000 	},
		{ Id : 36, Partid : 4006, Level : 6, Exp : 3500, Cost : 6000 	},
		{ Id : 37, Partid : 4007, Level : 7, Exp : 4000, Cost : 7000 	},
		{ Id : 38, Partid : 4008, Level : 8, Exp : 4500, Cost : 8000 	},
		{ Id : 39, Partid : 4009, Level : 9, Exp : 5000, Cost : 9000 	},
		{ Id : 40, Partid : 4010, Level : 10, Exp : 5500, Cost : 10000 	},
		{ Id : 41, Partid : 5001, Level : 1, Exp : 1000, Cost : 1000 	},
		{ Id : 42, Partid : 5002, Level : 2, Exp : 1500, Cost : 2000 	},
		{ Id : 43, Partid : 5003, Level : 3, Exp : 2000, Cost : 3000 	},
		{ Id : 44, Partid : 5004, Level : 4, Exp : 2500, Cost : 4000 	},
		{ Id : 45, Partid : 5005, Level : 5, Exp : 3000, Cost : 5000 	},
		{ Id : 46, Partid : 5006, Level : 6, Exp : 3500, Cost : 6000 	},
		{ Id : 47, Partid : 5007, Level : 7, Exp : 4000, Cost : 7000 	},
		{ Id : 48, Partid : 5008, Level : 8, Exp : 4500, Cost : 8000 	},
		{ Id : 49, Partid : 5009, Level : 9, Exp : 5000, Cost : 9000 	},
		{ Id : 50, Partid : 5010, Level : 10, Exp : 5500, Cost : 10000 	}
	]


// Id
export var TCarPartLevelupById : game.Dictionary<table.ITCarPartLevelupDefine> = {}
function readTCarPartLevelupById(){
  for(let rec of TCarPartLevelup) {
    TCarPartLevelupById[rec.Id] = rec; 
  }
}
readTCarPartLevelupById();
}

