// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TCarPartLevelup : table.ITCarPartLevelupDefine[] = [
		{ Id : 1, Partid : 1001, Level : 1, Exp : 1000, Cost : 1000 	}
	]


// Id
export var TCarPartLevelupById : game.Dictionary<table.ITCarPartLevelupDefine> = {}
function readTCarPartLevelupById(){
  for(let rec of TCarPartLevelup) {
    TCarPartLevelupById[rec.Id] = rec; 
  }
}
readTCarPartLevelupById();
}

