// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TCarPartLevelup : table.ITCarPartLevelupDefine[] = [
		{ Id : 1, Quality : 1, Level : 1, Exp : 1000, Cost : 1000 	},
		{ Id : 2, Quality : 1, Level : 2, Exp : 1500, Cost : 2000 	},
		{ Id : 3, Quality : 1, Level : 3, Exp : 2000, Cost : 3000 	},
		{ Id : 4, Quality : 1, Level : 4, Exp : 2500, Cost : 4000 	},
		{ Id : 5, Quality : 1, Level : 5, Exp : 3000, Cost : 5000 	},
		{ Id : 6, Quality : 1, Level : 6, Exp : 3500, Cost : 6000 	},
		{ Id : 7, Quality : 1, Level : 7, Exp : 4000, Cost : 7000 	},
		{ Id : 8, Quality : 1, Level : 8, Exp : 4500, Cost : 8000 	},
		{ Id : 9, Quality : 1, Level : 9, Exp : 5000, Cost : 9000 	},
		{ Id : 10, Quality : 1, Level : 10, Exp : 5500, Cost : 10000 	},
		{ Id : 11, Quality : 2, Level : 1, Exp : 1000, Cost : 1000 	},
		{ Id : 12, Quality : 2, Level : 2, Exp : 1500, Cost : 2000 	},
		{ Id : 13, Quality : 2, Level : 3, Exp : 2000, Cost : 3000 	},
		{ Id : 14, Quality : 2, Level : 4, Exp : 2500, Cost : 4000 	},
		{ Id : 15, Quality : 2, Level : 5, Exp : 3000, Cost : 5000 	},
		{ Id : 16, Quality : 2, Level : 6, Exp : 3500, Cost : 6000 	},
		{ Id : 17, Quality : 2, Level : 7, Exp : 4000, Cost : 7000 	},
		{ Id : 18, Quality : 2, Level : 8, Exp : 4500, Cost : 8000 	},
		{ Id : 19, Quality : 2, Level : 9, Exp : 5000, Cost : 9000 	},
		{ Id : 20, Quality : 2, Level : 10, Exp : 5500, Cost : 10000 	},
		{ Id : 21, Quality : 3, Level : 1, Exp : 1000, Cost : 1000 	},
		{ Id : 22, Quality : 3, Level : 2, Exp : 1500, Cost : 2000 	},
		{ Id : 23, Quality : 3, Level : 3, Exp : 2000, Cost : 3000 	},
		{ Id : 24, Quality : 3, Level : 4, Exp : 2500, Cost : 4000 	},
		{ Id : 25, Quality : 3, Level : 5, Exp : 3000, Cost : 5000 	},
		{ Id : 26, Quality : 3, Level : 6, Exp : 3500, Cost : 6000 	},
		{ Id : 27, Quality : 3, Level : 7, Exp : 4000, Cost : 7000 	},
		{ Id : 28, Quality : 3, Level : 8, Exp : 4500, Cost : 8000 	},
		{ Id : 29, Quality : 3, Level : 9, Exp : 5000, Cost : 9000 	},
		{ Id : 30, Quality : 3, Level : 10, Exp : 5500, Cost : 10000 	},
		{ Id : 31, Quality : 4, Level : 1, Exp : 1000, Cost : 1000 	},
		{ Id : 32, Quality : 4, Level : 2, Exp : 1500, Cost : 2000 	},
		{ Id : 33, Quality : 4, Level : 3, Exp : 2000, Cost : 3000 	},
		{ Id : 34, Quality : 4, Level : 4, Exp : 2500, Cost : 4000 	},
		{ Id : 35, Quality : 4, Level : 5, Exp : 3000, Cost : 5000 	},
		{ Id : 36, Quality : 4, Level : 6, Exp : 3500, Cost : 6000 	},
		{ Id : 37, Quality : 4, Level : 7, Exp : 4000, Cost : 7000 	},
		{ Id : 38, Quality : 4, Level : 8, Exp : 4500, Cost : 8000 	},
		{ Id : 39, Quality : 4, Level : 9, Exp : 5000, Cost : 9000 	},
		{ Id : 40, Quality : 4, Level : 10, Exp : 5500, Cost : 10000 	},
		{ Id : 41, Quality : 5, Level : 1, Exp : 1000, Cost : 1000 	},
		{ Id : 42, Quality : 5, Level : 2, Exp : 1500, Cost : 2000 	},
		{ Id : 43, Quality : 5, Level : 3, Exp : 2000, Cost : 3000 	},
		{ Id : 44, Quality : 5, Level : 4, Exp : 2500, Cost : 4000 	},
		{ Id : 45, Quality : 5, Level : 5, Exp : 3000, Cost : 5000 	},
		{ Id : 46, Quality : 5, Level : 6, Exp : 3500, Cost : 6000 	},
		{ Id : 47, Quality : 5, Level : 7, Exp : 4000, Cost : 7000 	},
		{ Id : 48, Quality : 5, Level : 8, Exp : 4500, Cost : 8000 	},
		{ Id : 49, Quality : 5, Level : 9, Exp : 5000, Cost : 9000 	},
		{ Id : 50, Quality : 5, Level : 10, Exp : 5500, Cost : 10000 	}
	]


// Id
export var TCarPartLevelupById : game.Dictionary<table.ITCarPartLevelupDefine> = {}
function readTCarPartLevelupById(){
  for(let rec of TCarPartLevelup) {
    TCarPartLevelupById[rec.Id] = rec; 
  }
}
readTCarPartLevelupById();
}

