// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TCarShop : table.ITCarShopDefine[] = [
		{ Id : 1, Carid : 1001, Price : 100 	},
		{ Id : 2, Carid : 1002, Price : 100 	},
		{ Id : 3, Carid : 1003, Price : 100 	},
		{ Id : 4, Carid : 1004, Price : 100 	},
		{ Id : 5, Carid : 1005, Price : 100 	},
		{ Id : 6, Carid : 1006, Price : 100 	}
	]


// Id
export var TCarShopById : game.Dictionary<table.ITCarShopDefine> = {}
function readTCarShopById(){
  for(let rec of TCarShop) {
    TCarShopById[rec.Id] = rec; 
  }
}
readTCarShopById();
}

