// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TCitys : table.ITCitysDefine[] = [
		{ Id : 10001, Type : 1, Superior : 0, Name : "北京" 	},
		{ Id : 10002, Type : 1, Superior : 0, Name : "上海" 	},
		{ Id : 10003, Type : 1, Superior : 0, Name : "天津" 	},
		{ Id : 10004, Type : 1, Superior : 0, Name : "重庆" 	},
		{ Id : 10005, Type : 1, Superior : 0, Name : "河北" 	},
		{ Id : 20001, Type : 2, Superior : 10002, Name : "黄埔区" 	}
	]


// Id
export var TCitysById : game.Dictionary<table.ITCitysDefine> = {}
function readTCitysById(){
  for(let rec of TCitys) {
    TCitysById[rec.Id] = rec; 
  }
}
readTCitysById();
}

