// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var Equip : table.IEquipDefine[] = [
		{ Id : 101, Name : "头盔", Desc : "装备获得效果", Pos : 1, SuitId : 0, LoadPoint : [  ], Path : "item_json.101", Skill : [ "1", "2" ], Price : 10, CoinType : 1 	},
		{ Id : 102, Name : "头盔", Desc : "装备获得效果", Pos : 1, SuitId : 1, LoadPoint : [  ], Path : "item_json.102", Skill : [ "1", "2" ], Price : 10, CoinType : 1 	},
		{ Id : 201, Name : "上衣", Desc : "装备获得效果", Pos : 2, SuitId : 0, LoadPoint : [  ], Path : "item_json.201", Skill : [ "1", "3" ], Price : 10, CoinType : 1 	},
		{ Id : 202, Name : "上衣", Desc : "装备获得效果", Pos : 2, SuitId : 1, LoadPoint : [  ], Path : "item_json.202", Skill : [ "1", "3" ], Price : 10, CoinType : 1 	},
		{ Id : 301, Name : "裤子", Desc : "装备获得效果", Pos : 3, SuitId : 0, LoadPoint : [  ], Path : "item_json.301", Skill : [ "1", "4" ], Price : 10, CoinType : 1 	},
		{ Id : 302, Name : "裤子", Desc : "装备获得效果", Pos : 3, SuitId : 1, LoadPoint : [  ], Path : "item_json.302", Skill : [ "1", "4" ], Price : 10, CoinType : 1 	},
		{ Id : 401, Name : "鞋子", Desc : "装备获得效果", Pos : 4, SuitId : 0, LoadPoint : [  ], Path : "item_json.401", Skill : [ "1", "5" ], Price : 10, CoinType : 1 	},
		{ Id : 402, Name : "鞋子", Desc : "装备获得效果", Pos : 4, SuitId : 1, LoadPoint : [  ], Path : "item_json.402", Skill : [ "1", "5" ], Price : 10, CoinType : 1 	},
		{ Id : 501, Name : "棒棒", Desc : "装备获得效果", Pos : 5, SuitId : 0, LoadPoint : [  ], Path : "item_json.501", Skill : [ "1", "6" ], Price : 10, CoinType : 1 	},
		{ Id : 502, Name : "棒棒", Desc : "装备获得效果", Pos : 5, SuitId : 1, LoadPoint : [  ], Path : "item_json.502", Skill : [ "1", "6" ], Price : 10, CoinType : 1 	},
		{ Id : 601, Name : "翅膀", Desc : "装备获得效果", Pos : 6, SuitId : 0, LoadPoint : [  ], Path : "item_json.601", Skill : [ "1", "7" ], Price : 10, CoinType : 1 	},
		{ Id : 602, Name : "翅膀", Desc : "装备获得效果", Pos : 6, SuitId : 1, LoadPoint : [  ], Path : "item_json.602", Skill : [ "1", "7" ], Price : 10, CoinType : 1 	},
		{ Id : 701, Name : "套装1", Desc : "装备获得效果", Pos : 7, SuitId : 1, LoadPoint : [  ], Path : "item_json.701", Skill : [ "1", "8" ], Price : 10, CoinType : 1 	}
	]


// Id
export var EquipById : game.Dictionary<table.IEquipDefine> = {}
function readEquipById(){
  for(let rec of Equip) {
    EquipById[rec.Id] = rec; 
  }
}
readEquipById();
}

