// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var THousePartsShop : table.ITHousePartsShopDefine[] = [
	]


// Id
export var THousePartsShopById : game.Dictionary<table.ITHousePartsShopDefine> = {}
function readTHousePartsShopById(){
  for(let rec of THousePartsShop) {
    THousePartsShopById[rec.Id] = rec; 
  }
}
readTHousePartsShopById();
}

