// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var THouseCell : table.ITHouseCellDefine[] = [
		{ Id : 1001, Type : 1, MaxLevel : 8, ProduceGold : 1, ProduceTime : 10, ProduceItem : "", LevelUpCost : 5, LevelUpNeedItem : "", Des : "客厅", IncomePerSecond : 0.1, UnlockGold : 0 	},
		{ Id : 1002, Type : 1, MaxLevel : 8, ProduceGold : 36, ProduceTime : 45, ProduceItem : "", LevelUpCost : 360, LevelUpNeedItem : "", Des : "客厅", IncomePerSecond : 0.8, UnlockGold : 0 	},
		{ Id : 1003, Type : 1, MaxLevel : 8, ProduceGold : 120, ProduceTime : 80, ProduceItem : "", LevelUpCost : 1800, LevelUpNeedItem : "", Des : "客厅", IncomePerSecond : 1.5, UnlockGold : 0 	},
		{ Id : 1004, Type : 1, MaxLevel : 8, ProduceGold : 253, ProduceTime : 115, ProduceItem : "", LevelUpCost : 5060, LevelUpNeedItem : "", Des : "客厅", IncomePerSecond : 2.2, UnlockGold : 0 	},
		{ Id : 1005, Type : 1, MaxLevel : 8, ProduceGold : 435, ProduceTime : 150, ProduceItem : "", LevelUpCost : 8700, LevelUpNeedItem : "", Des : "客厅", IncomePerSecond : 2.9, UnlockGold : 0 	},
		{ Id : 1006, Type : 1, MaxLevel : 8, ProduceGold : 666, ProduceTime : 185, ProduceItem : "", LevelUpCost : 13320, LevelUpNeedItem : "", Des : "客厅", IncomePerSecond : 3.6, UnlockGold : 0 	},
		{ Id : 1007, Type : 1, MaxLevel : 8, ProduceGold : 946, ProduceTime : 220, ProduceItem : "", LevelUpCost : 18920, LevelUpNeedItem : "", Des : "客厅", IncomePerSecond : 4.3, UnlockGold : 0 	},
		{ Id : 1008, Type : 1, MaxLevel : 8, ProduceGold : 1275, ProduceTime : 255, ProduceItem : "", LevelUpCost : 0, LevelUpNeedItem : "", Des : "客厅", IncomePerSecond : 5, UnlockGold : 0 	},
		{ Id : 2001, Type : 2, MaxLevel : 8, ProduceGold : 3, ProduceTime : 15, ProduceItem : "", LevelUpCost : 15, LevelUpNeedItem : "", Des : "卧室", IncomePerSecond : 0.2, UnlockGold : 150 	},
		{ Id : 2002, Type : 2, MaxLevel : 8, ProduceGold : 45, ProduceTime : 50, ProduceItem : "", LevelUpCost : 450, LevelUpNeedItem : "", Des : "卧室", IncomePerSecond : 0.9, UnlockGold : 0 	},
		{ Id : 2003, Type : 2, MaxLevel : 8, ProduceGold : 136, ProduceTime : 85, ProduceItem : "", LevelUpCost : 2040, LevelUpNeedItem : "", Des : "卧室", IncomePerSecond : 1.6, UnlockGold : 0 	},
		{ Id : 2004, Type : 2, MaxLevel : 8, ProduceGold : 276, ProduceTime : 120, ProduceItem : "", LevelUpCost : 5520, LevelUpNeedItem : "", Des : "卧室", IncomePerSecond : 2.3, UnlockGold : 0 	},
		{ Id : 2005, Type : 2, MaxLevel : 8, ProduceGold : 465, ProduceTime : 155, ProduceItem : "", LevelUpCost : 9300, LevelUpNeedItem : "", Des : "卧室", IncomePerSecond : 3, UnlockGold : 0 	},
		{ Id : 2006, Type : 2, MaxLevel : 8, ProduceGold : 703, ProduceTime : 190, ProduceItem : "", LevelUpCost : 14060, LevelUpNeedItem : "", Des : "卧室", IncomePerSecond : 3.7, UnlockGold : 0 	},
		{ Id : 2007, Type : 2, MaxLevel : 8, ProduceGold : 990, ProduceTime : 225, ProduceItem : "", LevelUpCost : 19800, LevelUpNeedItem : "", Des : "卧室", IncomePerSecond : 4.4, UnlockGold : 0 	},
		{ Id : 2008, Type : 2, MaxLevel : 8, ProduceGold : 1326, ProduceTime : 260, ProduceItem : "", LevelUpCost : 0, LevelUpNeedItem : "", Des : "卧室", IncomePerSecond : 5.1, UnlockGold : 0 	},
		{ Id : 3001, Type : 3, MaxLevel : 8, ProduceGold : 6, ProduceTime : 20, ProduceItem : "", LevelUpCost : 30, LevelUpNeedItem : "", Des : "厕所", IncomePerSecond : 0.3, UnlockGold : 300 	},
		{ Id : 3002, Type : 3, MaxLevel : 8, ProduceGold : 55, ProduceTime : 55, ProduceItem : "", LevelUpCost : 550, LevelUpNeedItem : "", Des : "厕所", IncomePerSecond : 1, UnlockGold : 0 	},
		{ Id : 3003, Type : 3, MaxLevel : 8, ProduceGold : 153, ProduceTime : 90, ProduceItem : "", LevelUpCost : 2295, LevelUpNeedItem : "", Des : "厕所", IncomePerSecond : 1.7, UnlockGold : 0 	},
		{ Id : 3004, Type : 3, MaxLevel : 8, ProduceGold : 300, ProduceTime : 125, ProduceItem : "", LevelUpCost : 6000, LevelUpNeedItem : "", Des : "厕所", IncomePerSecond : 2.4, UnlockGold : 0 	},
		{ Id : 3005, Type : 3, MaxLevel : 8, ProduceGold : 496, ProduceTime : 160, ProduceItem : "", LevelUpCost : 9920, LevelUpNeedItem : "", Des : "厕所", IncomePerSecond : 3.1, UnlockGold : 0 	},
		{ Id : 3006, Type : 3, MaxLevel : 8, ProduceGold : 741, ProduceTime : 195, ProduceItem : "", LevelUpCost : 14820, LevelUpNeedItem : "", Des : "厕所", IncomePerSecond : 3.8, UnlockGold : 0 	},
		{ Id : 3007, Type : 3, MaxLevel : 8, ProduceGold : 1035, ProduceTime : 230, ProduceItem : "", LevelUpCost : 20700, LevelUpNeedItem : "", Des : "厕所", IncomePerSecond : 4.5, UnlockGold : 0 	},
		{ Id : 3008, Type : 3, MaxLevel : 8, ProduceGold : 1378, ProduceTime : 265, ProduceItem : "", LevelUpCost : 0, LevelUpNeedItem : "", Des : "厕所", IncomePerSecond : 5.2, UnlockGold : 0 	},
		{ Id : 4001, Type : 4, MaxLevel : 8, ProduceGold : 10, ProduceTime : 25, ProduceItem : "", LevelUpCost : 50, LevelUpNeedItem : "", Des : "厨房", IncomePerSecond : 0.4, UnlockGold : 500 	},
		{ Id : 4002, Type : 4, MaxLevel : 8, ProduceGold : 66, ProduceTime : 60, ProduceItem : "", LevelUpCost : 660, LevelUpNeedItem : "", Des : "厨房", IncomePerSecond : 1.1, UnlockGold : 0 	},
		{ Id : 4003, Type : 4, MaxLevel : 8, ProduceGold : 171, ProduceTime : 95, ProduceItem : "", LevelUpCost : 2565, LevelUpNeedItem : "", Des : "厨房", IncomePerSecond : 1.8, UnlockGold : 0 	},
		{ Id : 4004, Type : 4, MaxLevel : 8, ProduceGold : 325, ProduceTime : 130, ProduceItem : "", LevelUpCost : 6500, LevelUpNeedItem : "", Des : "厨房", IncomePerSecond : 2.5, UnlockGold : 0 	},
		{ Id : 4005, Type : 4, MaxLevel : 8, ProduceGold : 528, ProduceTime : 165, ProduceItem : "", LevelUpCost : 10560, LevelUpNeedItem : "", Des : "厨房", IncomePerSecond : 3.2, UnlockGold : 0 	},
		{ Id : 4006, Type : 4, MaxLevel : 8, ProduceGold : 780, ProduceTime : 200, ProduceItem : "", LevelUpCost : 15600, LevelUpNeedItem : "", Des : "厨房", IncomePerSecond : 3.9, UnlockGold : 0 	},
		{ Id : 4007, Type : 4, MaxLevel : 8, ProduceGold : 1081, ProduceTime : 235, ProduceItem : "", LevelUpCost : 21620, LevelUpNeedItem : "", Des : "厨房", IncomePerSecond : 4.6, UnlockGold : 0 	},
		{ Id : 4008, Type : 4, MaxLevel : 8, ProduceGold : 1431, ProduceTime : 270, ProduceItem : "", LevelUpCost : 0, LevelUpNeedItem : "", Des : "厨房", IncomePerSecond : 5.3, UnlockGold : 0 	},
		{ Id : 5001, Type : 5, MaxLevel : 8, ProduceGold : 15, ProduceTime : 30, ProduceItem : "", LevelUpCost : 75, LevelUpNeedItem : "", Des : "卧室", IncomePerSecond : 0.5, UnlockGold : 750 	},
		{ Id : 5002, Type : 5, MaxLevel : 8, ProduceGold : 78, ProduceTime : 65, ProduceItem : "", LevelUpCost : 780, LevelUpNeedItem : "", Des : "卧室", IncomePerSecond : 1.2, UnlockGold : 0 	},
		{ Id : 5003, Type : 5, MaxLevel : 8, ProduceGold : 190, ProduceTime : 100, ProduceItem : "", LevelUpCost : 2850, LevelUpNeedItem : "", Des : "卧室", IncomePerSecond : 1.9, UnlockGold : 0 	},
		{ Id : 5004, Type : 5, MaxLevel : 8, ProduceGold : 351, ProduceTime : 135, ProduceItem : "", LevelUpCost : 7020, LevelUpNeedItem : "", Des : "卧室", IncomePerSecond : 2.6, UnlockGold : 0 	},
		{ Id : 5005, Type : 5, MaxLevel : 8, ProduceGold : 561, ProduceTime : 170, ProduceItem : "", LevelUpCost : 11220, LevelUpNeedItem : "", Des : "卧室", IncomePerSecond : 3.3, UnlockGold : 0 	},
		{ Id : 5006, Type : 5, MaxLevel : 8, ProduceGold : 820, ProduceTime : 205, ProduceItem : "", LevelUpCost : 16400, LevelUpNeedItem : "", Des : "卧室", IncomePerSecond : 4, UnlockGold : 0 	},
		{ Id : 5007, Type : 5, MaxLevel : 8, ProduceGold : 1128, ProduceTime : 240, ProduceItem : "", LevelUpCost : 22560, LevelUpNeedItem : "", Des : "卧室", IncomePerSecond : 4.7, UnlockGold : 0 	},
		{ Id : 5008, Type : 5, MaxLevel : 8, ProduceGold : 1485, ProduceTime : 275, ProduceItem : "", LevelUpCost : 0, LevelUpNeedItem : "", Des : "卧室", IncomePerSecond : 5.4, UnlockGold : 0 	},
		{ Id : 6001, Type : 6, MaxLevel : 8, ProduceGold : 21, ProduceTime : 35, ProduceItem : "", LevelUpCost : 105, LevelUpNeedItem : "", Des : "卧室", IncomePerSecond : 0.6, UnlockGold : 1050 	},
		{ Id : 6002, Type : 6, MaxLevel : 8, ProduceGold : 91, ProduceTime : 70, ProduceItem : "", LevelUpCost : 910, LevelUpNeedItem : "", Des : "卧室", IncomePerSecond : 1.3, UnlockGold : 0 	},
		{ Id : 6003, Type : 6, MaxLevel : 8, ProduceGold : 210, ProduceTime : 105, ProduceItem : "", LevelUpCost : 3150, LevelUpNeedItem : "", Des : "卧室", IncomePerSecond : 2, UnlockGold : 0 	},
		{ Id : 6004, Type : 6, MaxLevel : 8, ProduceGold : 378, ProduceTime : 140, ProduceItem : "", LevelUpCost : 7560, LevelUpNeedItem : "", Des : "卧室", IncomePerSecond : 2.7, UnlockGold : 0 	},
		{ Id : 6005, Type : 6, MaxLevel : 8, ProduceGold : 595, ProduceTime : 175, ProduceItem : "", LevelUpCost : 11900, LevelUpNeedItem : "", Des : "卧室", IncomePerSecond : 3.4, UnlockGold : 0 	},
		{ Id : 6006, Type : 6, MaxLevel : 8, ProduceGold : 861, ProduceTime : 210, ProduceItem : "", LevelUpCost : 17220, LevelUpNeedItem : "", Des : "卧室", IncomePerSecond : 4.1, UnlockGold : 0 	},
		{ Id : 6007, Type : 6, MaxLevel : 8, ProduceGold : 1176, ProduceTime : 245, ProduceItem : "", LevelUpCost : 23520, LevelUpNeedItem : "", Des : "卧室", IncomePerSecond : 4.8, UnlockGold : 0 	},
		{ Id : 6008, Type : 6, MaxLevel : 8, ProduceGold : 1540, ProduceTime : 280, ProduceItem : "", LevelUpCost : 0, LevelUpNeedItem : "", Des : "卧室", IncomePerSecond : 5.5, UnlockGold : 0 	},
		{ Id : 7001, Type : 7, MaxLevel : 8, ProduceGold : 28, ProduceTime : 40, ProduceItem : "", LevelUpCost : 140, LevelUpNeedItem : "", Des : "卧室", IncomePerSecond : 0.7, UnlockGold : 1400 	},
		{ Id : 7002, Type : 7, MaxLevel : 8, ProduceGold : 105, ProduceTime : 75, ProduceItem : "", LevelUpCost : 1050, LevelUpNeedItem : "", Des : "卧室", IncomePerSecond : 1.4, UnlockGold : 0 	},
		{ Id : 7003, Type : 7, MaxLevel : 8, ProduceGold : 231, ProduceTime : 110, ProduceItem : "", LevelUpCost : 3465, LevelUpNeedItem : "", Des : "卧室", IncomePerSecond : 2.1, UnlockGold : 0 	},
		{ Id : 7004, Type : 7, MaxLevel : 8, ProduceGold : 406, ProduceTime : 145, ProduceItem : "", LevelUpCost : 8120, LevelUpNeedItem : "", Des : "卧室", IncomePerSecond : 2.8, UnlockGold : 0 	},
		{ Id : 7005, Type : 7, MaxLevel : 8, ProduceGold : 630, ProduceTime : 180, ProduceItem : "", LevelUpCost : 12600, LevelUpNeedItem : "", Des : "卧室", IncomePerSecond : 3.5, UnlockGold : 0 	},
		{ Id : 7006, Type : 7, MaxLevel : 8, ProduceGold : 903, ProduceTime : 215, ProduceItem : "", LevelUpCost : 18060, LevelUpNeedItem : "", Des : "卧室", IncomePerSecond : 4.2, UnlockGold : 0 	},
		{ Id : 7007, Type : 7, MaxLevel : 8, ProduceGold : 1225, ProduceTime : 250, ProduceItem : "", LevelUpCost : 24500, LevelUpNeedItem : "", Des : "卧室", IncomePerSecond : 4.9, UnlockGold : 0 	},
		{ Id : 7008, Type : 7, MaxLevel : 8, ProduceGold : 1596, ProduceTime : 285, ProduceItem : "", LevelUpCost : 0, LevelUpNeedItem : "", Des : "卧室", IncomePerSecond : 5.6, UnlockGold : 0 	}
	]


// Id
export var THouseCellById : game.Dictionary<table.ITHouseCellDefine> = {}
function readTHouseCellById(){
  for(let rec of THouseCell) {
    THouseCellById[rec.Id] = rec; 
  }
}
readTHouseCellById();
}

