// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var THouseCell : table.ITHouseCellDefine[] = [
		{ Id : 1001, Type : 1, MaxLevel : 5, ProduceGold : 100, ProduceTime : 10, LevelUpCost : 100, Des : "" 	},
		{ Id : 1002, Type : 1, MaxLevel : 5, ProduceGold : 200, ProduceTime : 20, LevelUpCost : 200, Des : "" 	},
		{ Id : 1003, Type : 1, MaxLevel : 5, ProduceGold : 300, ProduceTime : 30, LevelUpCost : 300, Des : "" 	},
		{ Id : 1004, Type : 1, MaxLevel : 5, ProduceGold : 400, ProduceTime : 40, LevelUpCost : 400, Des : "" 	},
		{ Id : 1005, Type : 1, MaxLevel : 5, ProduceGold : 500, ProduceTime : 50, LevelUpCost : 0, Des : "" 	},
		{ Id : 2001, Type : 2, MaxLevel : 5, ProduceGold : 10, ProduceTime : 10, LevelUpCost : 10, Des : "" 	},
		{ Id : 2002, Type : 2, MaxLevel : 5, ProduceGold : 20, ProduceTime : 20, LevelUpCost : 20, Des : "" 	},
		{ Id : 2003, Type : 2, MaxLevel : 5, ProduceGold : 30, ProduceTime : 30, LevelUpCost : 30, Des : "" 	},
		{ Id : 2004, Type : 2, MaxLevel : 5, ProduceGold : 40, ProduceTime : 40, LevelUpCost : 40, Des : "" 	},
		{ Id : 2005, Type : 2, MaxLevel : 5, ProduceGold : 50, ProduceTime : 50, LevelUpCost : 0, Des : "" 	},
		{ Id : 3001, Type : 3, MaxLevel : 5, ProduceGold : 1000, ProduceTime : 10, LevelUpCost : 1000, Des : "" 	},
		{ Id : 3002, Type : 3, MaxLevel : 5, ProduceGold : 2000, ProduceTime : 20, LevelUpCost : 2000, Des : "" 	},
		{ Id : 3003, Type : 3, MaxLevel : 5, ProduceGold : 3000, ProduceTime : 30, LevelUpCost : 3000, Des : "" 	},
		{ Id : 3004, Type : 3, MaxLevel : 5, ProduceGold : 4000, ProduceTime : 40, LevelUpCost : 4000, Des : "" 	},
		{ Id : 3005, Type : 3, MaxLevel : 5, ProduceGold : 5000, ProduceTime : 50, LevelUpCost : 0, Des : "" 	},
		{ Id : 4001, Type : 4, MaxLevel : 5, ProduceGold : 1000, ProduceTime : 10, LevelUpCost : 1000, Des : "" 	},
		{ Id : 4002, Type : 4, MaxLevel : 5, ProduceGold : 2000, ProduceTime : 20, LevelUpCost : 2000, Des : "" 	},
		{ Id : 4003, Type : 4, MaxLevel : 5, ProduceGold : 3000, ProduceTime : 30, LevelUpCost : 3000, Des : "" 	},
		{ Id : 4004, Type : 4, MaxLevel : 5, ProduceGold : 4000, ProduceTime : 40, LevelUpCost : 4000, Des : "" 	},
		{ Id : 4005, Type : 4, MaxLevel : 5, ProduceGold : 5000, ProduceTime : 50, LevelUpCost : 0, Des : "" 	}
	]


// Id
export var THouseCellById : game.Dictionary<table.ITHouseCellDefine> = {}
function readTHouseCellById(){
  for(let rec of THouseCell) {
    THouseCellById[rec.Id] = rec; 
  }
}
readTHouseCellById();
}

