// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var THouse : table.ITHouseDefine[] = [
		{ Id : 1001, ImageId : 1001, Type : 1, MaxLevel : 5, MaxCells : 4, Cells : "1-1|2-2|3-3|4-4", LevelUpCost : 50, LevelUpNeedItem : "", Des : "一居室" 	},
		{ Id : 1002, ImageId : 1001, Type : 1, MaxLevel : 5, MaxCells : 4, Cells : "1-1|2-2|3-3|4-4", LevelUpCost : 660, LevelUpNeedItem : "", Des : "一居室" 	},
		{ Id : 1003, ImageId : 1001, Type : 1, MaxLevel : 5, MaxCells : 4, Cells : "1-1|2-2|3-3|4-4", LevelUpCost : 2565, LevelUpNeedItem : "", Des : "一居室" 	},
		{ Id : 1004, ImageId : 1001, Type : 1, MaxLevel : 5, MaxCells : 4, Cells : "1-1|2-2|3-3|4-4", LevelUpCost : 6500, LevelUpNeedItem : "", Des : "一居室" 	},
		{ Id : 1005, ImageId : 1001, Type : 1, MaxLevel : 5, MaxCells : 4, Cells : "1-1|2-2|3-3|4-4", LevelUpCost : 0, LevelUpNeedItem : "", Des : "一居室" 	},
		{ Id : 2001, ImageId : 2001, Type : 2, MaxLevel : 6, MaxCells : 5, Cells : "1-1|2-2|3-3|4-4|5-5", LevelUpCost : 75, LevelUpNeedItem : "", Des : "二居室" 	},
		{ Id : 2002, ImageId : 2001, Type : 2, MaxLevel : 6, MaxCells : 5, Cells : "1-1|2-2|3-3|4-4|5-5", LevelUpCost : 780, LevelUpNeedItem : "", Des : "二居室" 	},
		{ Id : 2003, ImageId : 2001, Type : 2, MaxLevel : 6, MaxCells : 5, Cells : "1-1|2-2|3-3|4-4|5-5", LevelUpCost : 2850, LevelUpNeedItem : "", Des : "二居室" 	},
		{ Id : 2004, ImageId : 2001, Type : 2, MaxLevel : 6, MaxCells : 5, Cells : "1-1|2-2|3-3|4-4|5-5", LevelUpCost : 7020, LevelUpNeedItem : "", Des : "二居室" 	},
		{ Id : 2005, ImageId : 2001, Type : 2, MaxLevel : 6, MaxCells : 5, Cells : "1-1|2-2|3-3|4-4|5-5", LevelUpCost : 11220, LevelUpNeedItem : "", Des : "二居室" 	},
		{ Id : 2006, ImageId : 2001, Type : 2, MaxLevel : 6, MaxCells : 5, Cells : "1-1|2-2|3-3|4-4|5-5", LevelUpCost : 0, LevelUpNeedItem : "", Des : "二居室" 	},
		{ Id : 3001, ImageId : 3001, Type : 3, MaxLevel : 7, MaxCells : 6, Cells : "1-1|2-2|3-3|4-4|5-5|6-6", LevelUpCost : 105, LevelUpNeedItem : "", Des : "三居室" 	},
		{ Id : 3002, ImageId : 3001, Type : 3, MaxLevel : 7, MaxCells : 6, Cells : "1-1|2-2|3-3|4-4|5-5|6-6", LevelUpCost : 910, LevelUpNeedItem : "", Des : "三居室" 	},
		{ Id : 3003, ImageId : 3001, Type : 3, MaxLevel : 7, MaxCells : 6, Cells : "1-1|2-2|3-3|4-4|5-5|6-6", LevelUpCost : 3150, LevelUpNeedItem : "", Des : "三居室" 	},
		{ Id : 3004, ImageId : 3001, Type : 3, MaxLevel : 7, MaxCells : 6, Cells : "1-1|2-2|3-3|4-4|5-5|6-6", LevelUpCost : 7560, LevelUpNeedItem : "", Des : "三居室" 	},
		{ Id : 3005, ImageId : 3001, Type : 3, MaxLevel : 7, MaxCells : 6, Cells : "1-1|2-2|3-3|4-4|5-5|6-6", LevelUpCost : 11900, LevelUpNeedItem : "", Des : "三居室" 	},
		{ Id : 3006, ImageId : 3001, Type : 3, MaxLevel : 7, MaxCells : 6, Cells : "1-1|2-2|3-3|4-4|5-5|6-6", LevelUpCost : 17220, LevelUpNeedItem : "", Des : "三居室" 	},
		{ Id : 3007, ImageId : 3001, Type : 3, MaxLevel : 7, MaxCells : 6, Cells : "1-1|2-2|3-3|4-4|5-5|6-6", LevelUpCost : 0, LevelUpNeedItem : "", Des : "三居室" 	},
		{ Id : 4001, ImageId : 4001, Type : 4, MaxLevel : 8, MaxCells : 7, Cells : "1-1|2-2|3-3|4-4|5-5|6-6|7-7", LevelUpCost : 140, LevelUpNeedItem : "", Des : "四居室" 	},
		{ Id : 4002, ImageId : 4001, Type : 4, MaxLevel : 8, MaxCells : 7, Cells : "1-1|2-2|3-3|4-4|5-5|6-6|7-7", LevelUpCost : 1050, LevelUpNeedItem : "", Des : "四居室" 	},
		{ Id : 4003, ImageId : 4001, Type : 4, MaxLevel : 8, MaxCells : 7, Cells : "1-1|2-2|3-3|4-4|5-5|6-6|7-7", LevelUpCost : 3465, LevelUpNeedItem : "", Des : "四居室" 	},
		{ Id : 4004, ImageId : 4001, Type : 4, MaxLevel : 8, MaxCells : 7, Cells : "1-1|2-2|3-3|4-4|5-5|6-6|7-7", LevelUpCost : 8120, LevelUpNeedItem : "", Des : "四居室" 	},
		{ Id : 4005, ImageId : 4001, Type : 4, MaxLevel : 8, MaxCells : 7, Cells : "1-1|2-2|3-3|4-4|5-5|6-6|7-7", LevelUpCost : 12600, LevelUpNeedItem : "", Des : "四居室" 	},
		{ Id : 4006, ImageId : 4001, Type : 4, MaxLevel : 8, MaxCells : 7, Cells : "1-1|2-2|3-3|4-4|5-5|6-6|7-7", LevelUpCost : 18060, LevelUpNeedItem : "", Des : "四居室" 	},
		{ Id : 4007, ImageId : 4001, Type : 4, MaxLevel : 8, MaxCells : 7, Cells : "1-1|2-2|3-3|4-4|5-5|6-6|7-7", LevelUpCost : 24500, LevelUpNeedItem : "", Des : "四居室" 	},
		{ Id : 4008, ImageId : 4001, Type : 4, MaxLevel : 8, MaxCells : 7, Cells : "1-1|2-2|3-3|4-4|5-5|6-6|7-7", LevelUpCost : 0, LevelUpNeedItem : "", Des : "四居室" 	}
	]


// Id
export var THouseById : game.Dictionary<table.ITHouseDefine> = {}
function readTHouseById(){
  for(let rec of THouse) {
    THouseById[rec.Id] = rec; 
  }
}
readTHouseById();
}

