// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var THouse : table.ITHouseDefine[] = [
		{ Id : 1001, Type : 1, MaxLevel : 5, MaxCells : 4, Cells : "1-1|2-2|3-3|4-4", LevelUpCost : 400, Des : "" 	},
		{ Id : 1002, Type : 1, MaxLevel : 5, MaxCells : 4, Cells : "1-1|2-2|3-3|4-4", LevelUpCost : 6000, Des : "" 	},
		{ Id : 1003, Type : 1, MaxLevel : 5, MaxCells : 4, Cells : "1-1|2-2|3-3|4-4", LevelUpCost : 24400, Des : "" 	},
		{ Id : 1004, Type : 1, MaxLevel : 5, MaxCells : 4, Cells : "1-1|2-2|3-3|4-4", LevelUpCost : 63280, Des : "" 	},
		{ Id : 1005, Type : 1, MaxLevel : 5, MaxCells : 4, Cells : "1-1|2-2|3-3|4-4", LevelUpCost : 0, Des : "" 	},
		{ Id : 2001, Type : 2, MaxLevel : 5, MaxCells : 4, Cells : "1-1|2-2|3-3|4-4", LevelUpCost : 400, Des : "" 	},
		{ Id : 2002, Type : 2, MaxLevel : 5, MaxCells : 4, Cells : "1-1|2-2|3-3|4-4", LevelUpCost : 6000, Des : "" 	},
		{ Id : 2003, Type : 2, MaxLevel : 5, MaxCells : 4, Cells : "1-1|2-2|3-3|4-4", LevelUpCost : 24400, Des : "" 	},
		{ Id : 2004, Type : 2, MaxLevel : 5, MaxCells : 4, Cells : "1-1|2-2|3-3|4-4", LevelUpCost : 63280, Des : "" 	},
		{ Id : 2005, Type : 2, MaxLevel : 5, MaxCells : 4, Cells : "1-1|2-2|3-3|4-4", LevelUpCost : 0, Des : "" 	},
		{ Id : 3001, Type : 3, MaxLevel : 5, MaxCells : 3, Cells : "1-1|2-2|3-3", LevelUpCost : 400, Des : "" 	},
		{ Id : 3002, Type : 3, MaxLevel : 5, MaxCells : 3, Cells : "1-1|2-2|3-3", LevelUpCost : 6000, Des : "" 	},
		{ Id : 3003, Type : 3, MaxLevel : 5, MaxCells : 3, Cells : "1-1|2-2|3-3", LevelUpCost : 24400, Des : "" 	},
		{ Id : 3004, Type : 3, MaxLevel : 5, MaxCells : 3, Cells : "1-1|2-2|3-3", LevelUpCost : 63280, Des : "" 	},
		{ Id : 3005, Type : 3, MaxLevel : 5, MaxCells : 3, Cells : "1-1|2-2|3-3", LevelUpCost : 0, Des : "" 	},
		{ Id : 4001, Type : 4, MaxLevel : 5, MaxCells : 2, Cells : "1-1|2-2", LevelUpCost : 400, Des : "" 	},
		{ Id : 4002, Type : 4, MaxLevel : 5, MaxCells : 2, Cells : "1-1|2-2", LevelUpCost : 6000, Des : "" 	},
		{ Id : 4003, Type : 4, MaxLevel : 5, MaxCells : 2, Cells : "1-1|2-2", LevelUpCost : 24400, Des : "" 	},
		{ Id : 4004, Type : 4, MaxLevel : 5, MaxCells : 2, Cells : "1-1|2-2", LevelUpCost : 63280, Des : "" 	},
		{ Id : 4005, Type : 4, MaxLevel : 5, MaxCells : 2, Cells : "1-1|2-2", LevelUpCost : 0, Des : "" 	}
	]


// Id
export var THouseById : game.Dictionary<table.ITHouseDefine> = {}
function readTHouseById(){
  for(let rec of THouse) {
    THouseById[rec.Id] = rec; 
  }
}
readTHouseById();
}

