// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TLevelCarPart : table.ITLevelCarPartDefine[] = [
	]


// Id
export var TLevelCarPartById : game.Dictionary<table.ITLevelCarPartDefine> = {}
function readTLevelCarPartById(){
  for(let rec of TLevelCarPart) {
    TLevelCarPartById[rec.Id] = rec; 
  }
}
readTLevelCarPartById();
}

