// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TMapStore : table.ITMapStoreDefine[] = [
		{ Id : 110001, ShopId : 3001, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 110002, ShopId : 3001, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 110003, ShopId : 3001, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 110004, ShopId : 3001, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 110005, ShopId : 3001, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 110006, ShopId : 3001, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 110007, ShopId : 3001, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 110008, ShopId : 3001, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 110009, ShopId : 3001, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 110010, ShopId : 3001, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 110011, ShopId : 3001, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 110012, ShopId : 3001, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 110013, ShopId : 3001, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 110014, ShopId : 3001, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 120001, ShopId : 3003, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 120002, ShopId : 3003, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 120003, ShopId : 3003, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 120004, ShopId : 3003, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 120005, ShopId : 3003, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 130001, ShopId : 3002, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 130002, ShopId : 3002, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 130003, ShopId : 3002, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 130004, ShopId : 3002, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 130005, ShopId : 3002, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 130006, ShopId : 3002, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 130007, ShopId : 3002, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 130008, ShopId : 3002, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 130009, ShopId : 3002, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 130010, ShopId : 3002, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 130011, ShopId : 3002, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 130012, ShopId : 3002, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 130013, ShopId : 3002, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 130014, ShopId : 3002, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 130015, ShopId : 3002, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 130016, ShopId : 3002, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 130017, ShopId : 3002, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 130018, ShopId : 3002, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 130019, ShopId : 3002, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 130020, ShopId : 3002, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 130021, ShopId : 3002, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 130022, ShopId : 3002, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 130023, ShopId : 3002, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 130024, ShopId : 3002, MoneyType : 1, Price : 100, Nums : 1000 	},
		{ Id : 130025, ShopId : 3002, MoneyType : 1, Price : 100, Nums : 1000 	}
	]


// Id
export var TMapStoreById : game.Dictionary<table.ITMapStoreDefine> = {}
function readTMapStoreById(){
  for(let rec of TMapStore) {
    TMapStoreById[rec.Id] = rec; 
  }
}
readTMapStoreById();
}

