// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var Marquee : table.IMarqueeDefine[] = [
		{ Id : 1, Type : 1, Show : 0, Message : "恭喜【{0}】在{1}中获得冠军，获得奖励{2}" 	},
		{ Id : 2, Type : 2, Show : 0, Message : "百人大战{0}爆出奖池{1}，快来一起参与吧！" 	},
		{ Id : 3, Type : 3, Show : 0, Message : "" 	}
	]


// Id
export var MarqueeById : game.Dictionary<table.IMarqueeDefine> = {}
function readMarqueeById(){
  for(let rec of Marquee) {
    MarqueeById[rec.Id] = rec; 
  }
}
readMarqueeById();
}

