// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TParking : table.ITParkingDefine[] = [
		{ Id : 1001, Type : 1, RewardPercent : 80 	},
		{ Id : 1002, Type : 2, RewardPercent : 100 	}
	]


// Id
export var TParkingById : game.Dictionary<table.ITParkingDefine> = {}
function readTParkingById(){
  for(let rec of TParking) {
    TParkingById[rec.Id] = rec; 
  }
}
readTParkingById();
}

