// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var PayList : table.IPayListDefine[] = [
		{ Id : 1, AwardId : 601, Type : 1, IgnoreInPanel : 0, IconName : "jiubei_1", IsWhiteView : 0 	},
		{ Id : 2, AwardId : 602, Type : 1, IgnoreInPanel : 0, IconName : "jiubei_2", IsWhiteView : 0 	},
		{ Id : 3, AwardId : 603, Type : 1, IgnoreInPanel : 0, IconName : "jiubei_3", IsWhiteView : 0 	},
		{ Id : 4, AwardId : 604, Type : 1, IgnoreInPanel : 0, IconName : "jiubei_4", IsWhiteView : 0 	},
		{ Id : 5, AwardId : 605, Type : 1, IgnoreInPanel : 0, IconName : "jiubei_5", IsWhiteView : 0 	},
		{ Id : 6, AwardId : 606, Type : 1, IgnoreInPanel : 0, IconName : "jiubei_6", IsWhiteView : 0 	},
		{ Id : 7, AwardId : 607, Type : 2, IgnoreInPanel : 0, IconName : "mall_zs_1", IsWhiteView : 0 	},
		{ Id : 8, AwardId : 608, Type : 2, IgnoreInPanel : 0, IconName : "mall_zs_2", IsWhiteView : 0 	},
		{ Id : 9, AwardId : 609, Type : 2, IgnoreInPanel : 0, IconName : "mall_zs_3", IsWhiteView : 0 	},
		{ Id : 10, AwardId : 610, Type : 2, IgnoreInPanel : 0, IconName : "mall_zs_4", IsWhiteView : 0 	},
		{ Id : 11, AwardId : 611, Type : 2, IgnoreInPanel : 0, IconName : "mall_zs_5", IsWhiteView : 0 	},
		{ Id : 12, AwardId : 612, Type : 2, IgnoreInPanel : 0, IconName : "mall_zs_6", IsWhiteView : 0 	},
		{ Id : 13, AwardId : 613, Type : 3, IgnoreInPanel : 0, IconName : "vip_1", IsWhiteView : 0 	},
		{ Id : 14, AwardId : 614, Type : 3, IgnoreInPanel : 0, IconName : "vip_2", IsWhiteView : 0 	},
		{ Id : 15, AwardId : 615, Type : 3, IgnoreInPanel : 0, IconName : "vip_2", IsWhiteView : 0 	},
		{ Id : 16, AwardId : 827, Type : 4, IgnoreInPanel : 1, IconName : "monthCard1", IsWhiteView : 0 	},
		{ Id : 17, AwardId : 828, Type : 4, IgnoreInPanel : 1, IconName : "monthCard2", IsWhiteView : 0 	},
		{ Id : 18, AwardId : 104, Type : 5, IgnoreInPanel : 0, IconName : "xiaolaba_1", IsWhiteView : 0 	},
		{ Id : 19, AwardId : 105, Type : 5, IgnoreInPanel : 0, IconName : "xiaolaba_2", IsWhiteView : 0 	}
	]


// Id
export var PayListById : game.Dictionary<table.IPayListDefine> = {}
function readPayListById(){
  for(let rec of PayList) {
    PayListById[rec.Id] = rec; 
  }
}
readPayListById();
}

