// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TRecharge : table.ITRechargeDefine[] = [
		{ Id : 1, Price : 6, Info : "1200金币" 	},
		{ Id : 2, Price : 30, Info : "6000金币" 	},
		{ Id : 3, Price : 98, Info : "19600金币" 	},
		{ Id : 4, Price : 128, Info : "25600金币" 	},
		{ Id : 5, Price : 348, Info : "69600金币" 	},
		{ Id : 6, Price : 648, Info : "129600金币" 	}
	]


// Id
export var TRechargeById : game.Dictionary<table.ITRechargeDefine> = {}
function readTRechargeById(){
  for(let rec of TRecharge) {
    TRechargeById[rec.Id] = rec; 
  }
}
readTRechargeById();
}

