// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TRecharge : table.ITRechargeDefine[] = [
		{ Id : 1, Price : 6 	},
		{ Id : 2, Price : 30 	},
		{ Id : 3, Price : 98 	},
		{ Id : 4, Price : 128 	},
		{ Id : 5, Price : 348 	},
		{ Id : 6, Price : 648 	}
	]


// Id
export var TRechargeById : game.Dictionary<table.ITRechargeDefine> = {}
function readTRechargeById(){
  for(let rec of TRecharge) {
    TRechargeById[rec.Id] = rec; 
  }
}
readTRechargeById();
}

