// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TSign : table.ITSignDefine[] = [
		{ Id : 1, Gold : 1800, GoldEx : 0 	},
		{ Id : 2, Gold : 2200, GoldEx : 0 	},
		{ Id : 3, Gold : 2600, GoldEx : 3000 	},
		{ Id : 4, Gold : 3000, GoldEx : 0 	},
		{ Id : 5, Gold : 3400, GoldEx : 5000 	},
		{ Id : 6, Gold : 3800, GoldEx : 0 	},
		{ Id : 7, Gold : 5000, GoldEx : 8000 	}
	]


// Id
export var TSignById : game.Dictionary<table.ITSignDefine> = {}
function readTSignById(){
  for(let rec of TSign) {
    TSignById[rec.Id] = rec; 
  }
}
readTSignById();
}

