// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TSkill : table.ITSkillDefine[] = [
		{ Id : 1, Type : 1, Num : 1, NumPer : 0, Des : "贯穿弹+1" 	},
		{ Id : 2, Type : 2, Num : 2, NumPer : 0, Des : "双倍时间+2秒" 	},
		{ Id : 3, Type : 3, Num : 0, NumPer : 2, Des : "大招所需能量-2%" 	},
		{ Id : 4, Type : 4, Num : 0, NumPer : 5, Des : "金币奖励+5%" 	},
		{ Id : 5, Type : 5, Num : 0, NumPer : 10, Des : "事件间隔时间+10%" 	}
	]


// Id
export var TSkillById : game.Dictionary<table.ITSkillDefine> = {}
function readTSkillById(){
  for(let rec of TSkill) {
    TSkillById[rec.Id] = rec; 
  }
}
readTSkillById();
}

